"""
Phantom Evasion - Detection Report Generator

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import hashlib
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional


def generate_detection_report(
    payload_path: str,
    scan_result: Dict[str, Any],
    techniques_used: Dict[str, Any],
    iteration: int = 1,
    output_dir: str = "output",
) -> str:
    """Generate a Markdown detection report for a tested payload.

    Args:
        payload_path:    Path to the compiled payload binary.
        scan_result:     Dict returned by :func:`av_test.defender_scan.scan_with_defender`.
        techniques_used: Dict returned by :meth:`Obfuscator.apply_all_layers`.
        iteration:       Obfuscation iteration number.
        output_dir:      Directory in which to write the report.

    Returns:
        Absolute path to the generated Markdown report file.
    """
    timestamp = datetime.now(timezone.utc)
    ts_str = timestamp.strftime("%Y-%m-%dT%H-%M-%SZ")
    report_name = f"detection_report_{ts_str}_iter{iteration}.md"
    report_path = Path(output_dir) / report_name
    report_path.parent.mkdir(parents=True, exist_ok=True)

    # Payload metadata
    payload_size = _get_file_size(payload_path)
    payload_sha256 = _sha256_file(payload_path)

    # Detection status styling
    if scan_result.get("detected") is True:
        status_badge = "🔴 **DETECTED**"
    elif scan_result.get("detected") is False:
        status_badge = "🟢 **CLEAN**"
    else:
        status_badge = "⚪ **UNKNOWN / UNAVAILABLE**"

    # Techniques summary
    description = techniques_used.get("description", "N/A")
    enc_snippet = _truncate(techniques_used.get("encryption_code", ""), 300)
    edr_snippet = _truncate(techniques_used.get("edr_code", ""), 300)
    etw_snippet = _truncate(techniques_used.get("etw_code", ""), 300)

    report = f"""\
# Phantom Evasion – Detection Report

> **LEGAL DISCLAIMER:** This report was generated by the Phantom Evasion security
> research tool. For **authorized penetration testing and security research ONLY**.
> Users must have explicit written permission from the target system owner.

---

## Overview

| Field          | Value |
|----------------|-------|
| Timestamp (UTC) | `{timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")}` |
| Iteration       | {iteration} |
| Payload Path    | `{payload_path}` |
| Payload Size    | {payload_size} bytes |
| SHA-256         | `{payload_sha256}` |

---

## AV Detection Result

| AV Engine        | Result | Threat Name |
|------------------|--------|-------------|
| Windows Defender | {status_badge} | `{scan_result.get("threat_name", "")}` |

**Raw scanner output:**
```
{_truncate(scan_result.get("raw_output", "N/A"), 500)}
```

---

## Obfuscation Techniques Applied

```
{description}
```

### Layer 1 – Static Evasion (Encryption Code Snippet)
```c
{enc_snippet}
```

### Layer 2 – EDR Bypass (Code Snippet)
```c
{edr_snippet}
```

### Layer 3 – ETW/AMSI Bypass (Code Snippet)
```c
{etw_snippet}
```

---

## Recommendations

{"✅ Payload evaded detection. Proceed with authorized engagement." if scan_result.get("detected") is False else "❌ Payload detected. Consider rotating encryption scheme or adding more obfuscation layers."}

---

*Generated by [Phantom Evasion](https://github.com/phantom-evasion/phantom-evasion)*
*For authorized use only.*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    return str(report_path.resolve())


# ── Helpers ──────────────────────────────────────────────────────────────────

def _get_file_size(path: str) -> int:
    """Return the file size in bytes, or -1 if the file does not exist."""
    try:
        return os.path.getsize(path)
    except OSError:
        return -1


def _sha256_file(path: str) -> str:
    """Return the hex SHA-256 digest of a file, or 'N/A' on error."""
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError:
        return "N/A"


def _truncate(text: str, max_chars: int) -> str:
    """Truncate *text* to *max_chars* characters, appending '…' if needed."""
    if not text:
        return ""
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n… (truncated)"
