"""
Phantom Evasion - Control Flow Flattening Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import random
from typing import Dict, Any, List


def generate_control_flow_flattening() -> Dict[str, Any]:
    """Generate a C control-flow-flattening skeleton (switch-case state machine).

    Real-world CFF replaces structured control flow (if/else, loops) with a
    dispatcher loop driven by an opaque state variable, making decompilation
    and static analysis significantly harder.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    # Randomise state constants so each build looks different
    states: List[int] = random.sample(range(0x1000, 0xFFFF), 6)
    s_init, s_decrypt, s_bypass, s_inject, s_cleanup, s_done = states

    dispatcher_var = f"_state_{random.randint(100, 999)}"

    code = f"""\
#ifndef __PHANTOM_CONTROL_FLOW_FLATTEN__
#define __PHANTOM_CONTROL_FLOW_FLATTEN__
// Control Flow Flattening – generated by Phantom Evasion
// Layer 1 – Static Evasion
// State machine dispatcher replaces structured control flow.

static void run_flattened_loader(
        unsigned char *shellcode, size_t shellcode_len,
        DWORD target_pid) {{

    volatile unsigned int {dispatcher_var} = {hex(s_init)};

    while ({dispatcher_var} != {hex(s_done)}) {{
        switch ({dispatcher_var}) {{

        case {hex(s_init)}: {{
            // State: initialise – perform environment checks
            {dispatcher_var} = {hex(s_decrypt)};
            break;
        }}

        case {hex(s_decrypt)}: {{
            // State: decrypt shellcode in-place
            // (decryption routine injected by Phantom Evasion here)
            {dispatcher_var} = {hex(s_bypass)};
            break;
        }}

        case {hex(s_bypass)}: {{
            // State: apply EDR/ETW bypass
            {dispatcher_var} = {hex(s_inject)};
            break;
        }}

        case {hex(s_inject)}: {{
            // State: inject into target process
            {dispatcher_var} = {hex(s_cleanup)};
            break;
        }}

        case {hex(s_cleanup)}: {{
            // State: wipe artefacts from memory
            SecureZeroMemory(shellcode, shellcode_len);
            {dispatcher_var} = {hex(s_done)};
            break;
        }}

        default:
            {dispatcher_var} = {hex(s_done)};
            break;
        }}
    }}
}}
#endif /* __PHANTOM_CONTROL_FLOW_FLATTEN__ */
"""

    return {
        "code": code,
        "description": f"Control flow flattening (6-state machine, seeds: {hex(s_init)}…)",
        "layer": "Layer 1 - Static Evasion",
        "name": "control_flow_flatten",
    }
