"""
Phantom Evasion - Junk Code Generator

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import random
import string
from typing import Dict, Any


def _random_varname(length: int = 8) -> str:
    """Return a random C identifier."""
    first = random.choice(string.ascii_letters + "_")
    rest = "".join(random.choices(string.ascii_letters + string.digits + "_", k=length - 1))
    return first + rest


def _junk_loop() -> str:
    var = _random_varname()
    limit = random.randint(100, 9999)
    return f"""\
    {{
        volatile int {var} = 0;
        for (int _i = 0; _i < {limit}; _i++) {{
            {var} += _i * {random.randint(1, 100)};
            if ({var} > {random.randint(10000, 99999)}) {var} = 0;
        }}
        (void){var};
    }}"""


def _junk_math() -> str:
    a, b = _random_varname(), _random_varname()
    ops = ["+", "-", "*", "^", "|", "&"]
    op = random.choice(ops)
    v1, v2 = random.randint(1, 0xFFFF), random.randint(1, 0xFFFF)
    return f"""\
    {{
        volatile unsigned int {a} = {v1};
        volatile unsigned int {b} = {v2};
        {a} = {a} {op} {b};
        (void){a};
    }}"""


def _junk_conditional() -> str:
    var = _random_varname()
    val = random.randint(0, 0xFFFF)
    always_false = random.randint(0xFFFF + 1, 0xFFFFFFFF)
    return f"""\
    {{
        volatile unsigned long {var} = (unsigned long)GetTickCount64() & 0xFFFF;
        if ({var} == {always_false}UL) {{
            // Dead code – never reached
            {var} = {val};
            ExitProcess(0);
        }}
        (void){var};
    }}"""


def generate_junk_code(num_blocks: int = 5) -> Dict[str, Any]:
    """Generate random valid C code blocks that serve as junk/decoy code.

    These blocks contain loops, math operations, and dead conditionals that
    inflate binary entropy and confuse signature-based scanners.

    Args:
        num_blocks: Number of junk blocks to emit.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    generators = [_junk_loop, _junk_math, _junk_conditional]
    blocks = [random.choice(generators)() for _ in range(num_blocks)]

    fn_name = _random_varname(10)
    inner = "\n".join(blocks)

    code = f"""\
#ifndef __PHANTOM_JUNK_DEFINED__
#define __PHANTOM_JUNK_DEFINED__
// Junk Code – generated by Phantom Evasion
// Layer 1 – Static Evasion
static void {fn_name}(void) {{
{inner}
}}
#endif /* __PHANTOM_JUNK_DEFINED__ */
"""

    return {
        "code": code,
        "description": f"Junk code injection ({num_blocks} blocks)",
        "layer": "Layer 1 - Static Evasion",
        "name": "junk_code",
    }
