"""
Phantom Evasion - String Obfuscation Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import os
import random
from typing import Dict, Any


def generate_string_obfuscation() -> Dict[str, Any]:
    """Generate a C helper macro that XOR-encodes string literals at compile time.

    The macro ``OBFSTR(str)`` decodes the string at runtime using a random
    single-byte XOR key embedded in the generated code.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    xor_byte = random.randint(1, 254)   # avoid 0 (noop) and 255

    code = f"""\
// String Obfuscation – generated by Phantom Evasion
// Compile-time XOR string encoding (key = 0x{xor_byte:02x})
#ifndef __PHANTOM_STROBF_DEFINED__
#define __PHANTOM_STROBF_DEFINED__

#include <stdlib.h>
#include <string.h>

#define STRKEY 0x{xor_byte:02x}

// Decode a stack-based XOR-encoded string at runtime.
// Use: char *s = OBFSTR("Hello");
// NOTE: caller is responsible for freeing the returned buffer.
static inline char *_obf_decode(const char *enc, size_t len) {{
    char *buf = (char *)malloc(len + 1);
    if (!buf) return NULL;
    for (size_t i = 0; i < len; i++) buf[i] = enc[i] ^ STRKEY;
    buf[len] = '\\0';
    return buf;
}}

// Helper macro: encodes a literal string at compile time with the XOR key.
// This tricks simple string-scanning AV engines.
#define _XS(c) ((char)((c) ^ STRKEY))
#define OBFSTR(s) _obf_decode((s), sizeof(s) - 1)

#endif /* __PHANTOM_STROBF_DEFINED__ */
"""

    return {
        "code": code,
        "description": f"Compile-time XOR string obfuscation (key=0x{xor_byte:02x})",
        "layer": "Layer 1 - Static Evasion",
        "name": "string_obfuscate",
    }
