"""
Phantom Evasion - Environment Checks (VM/Sandbox/Debugger Detection)

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_env_checks() -> Dict[str, Any]:
    """Generate C code for VM, sandbox, and debugger detection.

    Checks performed:
        - ``IsDebuggerPresent`` / ``CheckRemoteDebuggerPresent``
        - Timing attack (``RDTSC`` delta)
        - Low processor count (< 2 cores typical in VMs)
        - Low physical RAM (< 4 GB common in sandboxes)
        - Known sandbox/AV process names via ``CreateToolhelp32Snapshot``
        - Mouse cursor movement check (no movement = automated sandbox)
        - Disk size check (sandboxes often have small disks < 60 GB)

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Environment Checks – VM/Sandbox/Debugger Detection
// Generated by Phantom Evasion – Layer 4 – Behavioral Evasion

#ifndef PHANTOM_ENV_CHECKS_INCLUDED
#define PHANTOM_ENV_CHECKS_INCLUDED

#include <windows.h>
#include <tlhelp32.h>
#include <intrin.h>
#include <stdint.h>

// ── Debugger detection ────────────────────────────────────────────────────────
static BOOL is_debugged(void) {
    if (IsDebuggerPresent()) return TRUE;

    BOOL remote = FALSE;
    CheckRemoteDebuggerPresent(GetCurrentProcess(), &remote);
    return remote;
}

// ── RDTSC timing attack ───────────────────────────────────────────────────────
static BOOL rdtsc_timing_check(void) {
    uint64_t t1 = __rdtsc();
    GetTickCount64();          // Non-trivial operation
    uint64_t t2 = __rdtsc();
    // Under a hypervisor the delta is typically much larger
    return (t2 - t1) > 500000ULL;
}

// ── CPU core count check ─────────────────────────────────────────────────────
static BOOL low_cpu_count(void) {
    SYSTEM_INFO si = {0};
    GetSystemInfo(&si);
    return si.dwNumberOfProcessors < 2;
}

// ── Physical RAM check ────────────────────────────────────────────────────────
static BOOL low_ram(void) {
    MEMORYSTATUSEX ms = { .dwLength = sizeof(ms) };
    GlobalMemoryStatusEx(&ms);
    // Sandboxes commonly have < 4 GB RAM
    return ms.ullTotalPhys < (4ULL * 1024 * 1024 * 1024);
}

// ── Disk size check ───────────────────────────────────────────────────────────
static BOOL small_disk(void) {
    ULARGE_INTEGER free_bytes, total_bytes, total_free;
    if (!GetDiskFreeSpaceExW(L"C:\\", &free_bytes, &total_bytes, &total_free))
        return FALSE;
    // < 60 GB total is suspicious
    return total_bytes.QuadPart < (60ULL * 1024 * 1024 * 1024);
}

// ── Known sandbox/AV process blacklist ───────────────────────────────────────
static const char *SANDBOX_PROCS[] = {
    "vmsrvc.exe", "vmusrvc.exe", "vmtoolsd.exe",
    "vboxservice.exe", "vboxtray.exe",
    "wireshark.exe", "procmon.exe", "procexp.exe",
    "pestudio.exe", "x64dbg.exe", "ollydbg.exe",
    "sandboxie.exe", "sbiesvc.exe",
    "cuckoo.exe", "analyzer.exe",
    NULL
};

static BOOL suspicious_process_running(void) {
    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (hSnap == INVALID_HANDLE_VALUE) return FALSE;

    PROCESSENTRY32 pe = { .dwSize = sizeof(pe) };
    BOOL found = FALSE;

    if (Process32First(hSnap, &pe)) {
        do {
            for (int i = 0; SANDBOX_PROCS[i]; i++) {
                if (_stricmp(pe.szExeFile, SANDBOX_PROCS[i]) == 0) {
                    found = TRUE;
                    break;
                }
            }
        } while (!found && Process32Next(hSnap, &pe));
    }
    CloseHandle(hSnap);
    return found;
}

// ── Mouse movement check ─────────────────────────────────────────────────────
static BOOL no_mouse_movement(void) {
    POINT p1, p2;
    GetCursorPos(&p1);
    Sleep(1500);
    GetCursorPos(&p2);
    return (p1.x == p2.x && p1.y == p2.y);
}

// ── Master check: returns TRUE if environment looks like a sandbox/VM ─────────
static BOOL is_sandbox(void) {
    if (is_debugged())                return TRUE;
    if (rdtsc_timing_check())         return TRUE;
    if (low_cpu_count())              return TRUE;
    if (low_ram())                    return TRUE;
    if (small_disk())                 return TRUE;
    if (suspicious_process_running()) return TRUE;
    if (no_mouse_movement())          return TRUE;
    return FALSE;
}

#endif /* PHANTOM_ENV_CHECKS_INCLUDED */
"""

    return {
        "code": code,
        "description": (
            "VM/sandbox/debugger detection: IsDebuggerPresent, RDTSC timing, "
            "CPU count, RAM, disk size, process blacklist, mouse movement"
        ),
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "env_checks",
    }
